### ISSUE TITLE
compute resource usage

### ISSUE THREAD

**Issue by catborise** [retspen/webvirtcloud#113]
Hi,

i am using webvirtmgr, it is awesome. 
i am also testing to use webvirtcloud. i installed and add some computes. it just works. 

but there is a problem, may be it is not a problem but missing feature.

in webvirtmgr, we can see the compute ram usage on the inventory list. it is very useful when you add a new vm. it could we very useful to see free ram percentage. could it be add to webvirtcloud?

thanks

**Comment by nitmir** [comment]
It is almost there: On compute menu, click on a compute name to display the compute overview with "CPU utilization" and "RAM utilization". CPU usage is in percent, RAM usage in MB.
Is it really useful to have ram usage in percent ?

**Comment by catborise** [comment]
yes i know that. but, think about that.

for creation of a vm
1. click compute, wait a few second to see populated value.
2. calculate on your mind. 
3. then pass to another computes to see their memory status(i have 8 compute node )
4. decide compute host to put on vm.
5. click + then begin to create vm.

is that sounds easy?
on webvirtmgr you can see all nodes used ram percentage on infrastructure tab. it is very helpful
