### ISSUE TITLE
rename admin account 

### ISSUE THREAD

**Issue by jb-alvarado** [retspen/webvirtcloud#115]
Hello,
is it possible to rename the admin account?

Regards

Jonathan

**Comment by nitmir** [comment]
Go to the webvirtcloud application directory and do `./manage.py createsuperuser`

In fact I think it is a bad idea to have default credential. The install procedure should call  `./manage.py createsuperuser`…

**Comment by jb-alvarado** [comment]
Thank you nitmir,
this works!
