### ISSUE TITLE
Error: Cannot recv data: Host key verification failed.: Connection reset by peer 

### ISSUE THREAD

**Issue by newzen** [retspen/webvirtcloud#120]
Hello,

Great job!

i receive this error while trying to add host via ssh

 Error: Cannot recv data: Host key verification failed.: Connection reset by peer 

from command line on machine running WebVirtCloud interfase

virsh -c qemu+ssh://root@192.168.13.119/system
Bienvenido a virsh, la terminal de virtualización interactiva.

Ingrese: 'help' para obtener ayuda con los comandos
       'quit' para salir

any help ?

and using python 
[root@phenom ~]# python
Python 2.7.5 (default, Nov 20 2015, 02:00:19) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import libvirt
> > > conn=libvirt.open("qemu+ssh://root@192.168.13.119/system")
> > > names = conn.listDefinedDomains()
> > > print names
> > > ['winXpDev01', 'vit32dev']

after that the error steel.

**Comment by savichev** [comment]
Maybe this will help
http://askubuntu.com/questions/45679/ssh-connection-problem-with-host-key-verification-failed-error

```
ssh-keygen -R hostname
```

**Comment by newzen** [comment]
Solved :+1: 
on server running WebVirtCloud

su -s /bin/bash nginx
ssh-keygen
ssh-copy-id root@192.168.13.119
exit

WebVirtCloud use nginx user for authenticate on kvm administered host.

thanks for great job.

**Comment by weijianwen** [comment]
Thank you, @newzen . I've encountered similar issues when importing KVM virtual machines from libvirt via ovrit webUI. Your approach works well.

On the host into which the KVM virtual machines will be imported, run

```
su -s /bin/bash vdsm
ssh-keygen
ssh-copy-id root@YOUR_KVM_HOST
you need to accept add key
```

**Comment by imperativa28** [comment]
> 
> 
> Thank you, @newzen . I've encountered similar issues when importing KVM virtual machines from libvirt via ovrit webUI. Your approach works well.
> 
> On the host into which the KVM virtual machines will be imported, run
> 
> ```
> su -s /bin/bash vdsm
> ssh-keygen
> ssh-copy-id root@YOUR_KVM_HOST
> you need to accept add key
> ```

Thank you @weijianwen . this helps me since [this](https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/html-single/virtual_machine_management_guide/index#Importing_a_Virtual_Machine_from_KVM) tutorial i tried to follow is kinda confusing since i don't have `vdsm` user activated by default

**Comment by wideweide** [comment]
https://github.com/retspen/webvirtcloud/wiki/Docker-Installation-&-Update

I use docker to install , but there is no nginx or vdsm, some idea?

**Comment by splusc** [comment]
> https://github.com/retspen/webvirtcloud/wiki/Docker-Installation-&-Update
> 
> I use docker to install , but there is no nginx or vdsm, some idea?

try ```www-data```
