### ISSUE TITLE
gstfsd - question!

### ISSUE THREAD

**Issue by thiagocpv** [retspen/webvirtcloud#13]
Hi there!

What is this gstfsd ? Need to install ? This package need install on kvm host or webvirtcloud host?

Thanks.

**Comment by retspen** [comment]
Hello

gstfsd - WebVirtCloud daemon for mananing filesystem in Instance (change root password or install ssh key). You need install this daemon on KVM server. You can install manually or run install script (wget -O - https://clck.ru/9V9fH | sudo sh).

**Comment by thiagocpv** [comment]
Very nice! Working fine in my Ubuntu VM!
Thanks.
