### ISSUE TITLE
Linked clone 

### ISSUE THREAD

**Issue by ppiccolo** [retspen/webvirtcloud#130]
Hello, 

very useful project, any suggestion on how to implement linked clone ?

tnx in advance

**Comment by savichev** [comment]
https://forums.unraid.net/topic/48837-creating-linked-clones/

sudo qemu-img create -f qcow2 -b /var/lib/libvirt/images/myreadonlyimage.qcow2 /var/lib/libvirt/images/mynewvm.qcow2
