### ISSUE TITLE
RelatedObjectDoesNotExist at /instance/2/inetlab-w7cli/   User has no userattributes.

### ISSUE THREAD

**Issue by ssbaksa** [retspen/webvirtcloud#135]
I have two servers (Ubuntu 16.04) running WebvirtCloud. On older one all works as expected but on newly installed one with latest WebvirtClud software I get this error when I try to access any of my virtual servers. Each server have an instance of WVC and is connected to libvirts on both of them.

Environment:

Request Method: GET
Request URL: http://192.168.252.162:80/instance/2/inetlab-w7cli/

Django Version: 1.8.11
Python Version: 2.7.12
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'computes',
 'console',
 'networks',
 'storages',
 'interfaces',
 'instances',
 'secrets',
 'logs',
 'accounts',
 'create')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.RemoteUserMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/srv/webvirtcloud/instances/views.py" in instance
  307.         user_quota_msg = check_user_quota(0, 0, 0, 0)
File "/srv/webvirtcloud/instances/views.py" in check_user_quota
  249.         ua = request.user.userattributes
File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/utils/functional.py" in inner
  226.         return func(self._wrapped, *args)
File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/db/models/fields/related.py" in __get__
  480.                     self.related.get_accessor_name()

Exception Type: RelatedObjectDoesNotExist at /instance/2/inetlab-w7cli/
Exception Value: User has no userattributes.

**Comment by ahromis** [comment]
I'm also seeing similar behavior, running on Ubuntu 17.04 and latest webvirtcloud master.

```
Environment:


Request Method: GET
Request URL: http://10.0.0.5:8000/instance/1/test2/

Django Version: 1.8.11
Python Version: 2.7.13
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'computes',
 'console',
 'networks',
 'storages',
 'interfaces',
 'instances',
 'secrets',
 'logs',
 'accounts',
 'create')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.RemoteUserMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')


Traceback:
File "/usr/share/webapps/webvirtcloud/venv/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/share/webapps/webvirtcloud/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/usr/share/webapps/webvirtcloud/instances/views.py" in instance
  307.         user_quota_msg = check_user_quota(0, 0, 0, 0)
File "/usr/share/webapps/webvirtcloud/instances/views.py" in check_user_quota
  249.         ua = request.user.userattributes
File "/usr/share/webapps/webvirtcloud/venv/lib/python2.7/site-packages/django/utils/functional.py" in inner
  226.         return func(self._wrapped, *args)
File "/usr/share/webapps/webvirtcloud/venv/lib/python2.7/site-packages/django/db/models/fields/related.py" in __get__
  480.                     self.related.get_accessor_name()

Exception Type: RelatedObjectDoesNotExist at /instance/1/test2/
Exception Value: User has no userattributes.

```

**Comment by ahromis** [comment]
It seems to work without issue when a user is created though. Just when using the admin user I get this error.

**Comment by cholletk** [comment]
I can solve this issue on my side by editing the admin user and login again (going trough the users tab and not Profile menu).

**Comment by zxing0214** [comment]
I'm also seeing similar behavior, running on Ubuntu 16.04 and latest webvirtcloud master.

**Comment by lsascha** [comment]
Had the same issue, edited Admin user using users tab without changing the password. got another error and now my password does no longer work. 😳
