### ISSUE TITLE
login webvirtcloud erros

### ISSUE THREAD

**Issue by letran3691** [retspen/webvirtcloud#143]
Help me.
Iam config done when login with user admin/admin then erros in image. I use centos7.4
https://user-images.githubusercontent.com/19284401/39852522-2f894324-5447-11e8-8304-0396e3859ea7.jpeg)
when i exec venv/bin/python manage.py migrate have mesg. what is has problem?
"?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG."

**Comment by honza801** [comment]
hi,
try to comment out TEMPLATE_DEBUG in webvirtcloud/settings.py
fous
