### ISSUE TITLE
Error with database, Still no login.

### ISSUE THREAD

**Issue by ssbaksa** [retspen/webvirtcloud#150]
After changing:

You have to change in settings.py to:

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    #'accounts.backends.MyRemoteUserBackend',
)

I can login only if I use old database so I decided to reinstall it from beginning (delete all and start with new pull). With new installation there is an error which say:

Request Method: | GET
-- | --
http://172.17.103.18:80/
1.8.11
OperationalError
no such table: django_session
/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py in execute, line 318
/srv/webvirtcloud/venv/bin/python2
2.7.12
['/srv/webvirtcloud',  '/srv/webvirtcloud/venv/bin',  '/srv/webvirtcloud/venv/lib/python2.7',  '/srv/webvirtcloud/venv/lib/python2.7/plat-x86_64-linux-gnu',  '/srv/webvirtcloud/venv/lib/python2.7/lib-tk',  '/srv/webvirtcloud/venv/lib/python2.7/lib-old',  '/srv/webvirtcloud/venv/lib/python2.7/lib-dynload',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/srv/webvirtcloud/venv/local/lib/python2.7/site-packages']
Fri, 1 Jun 2018 09:35:45 +0000

**Comment by honza801** [comment]
hi,
have you initialized db and application correctly?
fous

**Comment by ssbaksa** [comment]
I have more than 10 working installation of WebvirtCloud (older version)
and there was no problem with installation or initialisation so this is
much bigger issue than the one with improper initialisation of admin
account.
