### ISSUE TITLE
Almost all edit or change actions end in similar way:

### ISSUE THREAD

**Issue by ssbaksa** [retspen/webvirtcloud#157]
This one is from user edit but I can't edit, for example, compute node detail also.
I am posting both error pages.

Environment:

Request Method: POST
Request URL: http://172.17.252.166:80/computes/

Django Version: 1.8.11
Python Version: 2.7.12
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'computes',
 'console',
 'networks',
 'storages',
 'interfaces',
 'instances',
 'secrets',
 'logs',
 'accounts',
 'create',
 'datasource')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.RemoteUserMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/srv/webvirtcloud/computes/views.py" in computes
  126.                 compute.edit_details = data['details']

Exception Type: KeyError at /computes/
Exception Value: 'details'
---------------------------------------------------------------------------------------------------------

RelatedObjectDoesNotExist at /accounts/

User has no userattributes.

Request Method: 	POST
Request URL: 	http://172.17.252.166:80/accounts/
Django Version: 	1.8.11
Exception Type: 	RelatedObjectDoesNotExist
Exception Value: 	

User has no userattributes.

Exception Location: 	/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/db/models/fields/related.py in __get__, line 480
Python Executable: 	/srv/webvirtcloud/venv/bin/python2
Python Version: 	2.7.12
Python Path: 	

['/srv/webvirtcloud',
 '/srv/webvirtcloud/venv/bin',
 '/srv/webvirtcloud/venv/lib/python2.7',
 '/srv/webvirtcloud/venv/lib/python2.7/plat-x86_64-linux-gnu',
 '/srv/webvirtcloud/venv/lib/python2.7/lib-tk',
 '/srv/webvirtcloud/venv/lib/python2.7/lib-old',
 '/srv/webvirtcloud/venv/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/srv/webvirtcloud/venv/local/lib/python2.7/site-packages']

Server time: 	Mon, 2 Jul 2018 11:47:17 +0000

Environment:

Request Method: POST
Request URL: http://172.17.252.166:80/accounts/

Django Version: 1.8.11
Python Version: 2.7.12
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'computes',
 'console',
 'networks',
 'storages',
 'interfaces',
 'instances',
 'secrets',
 'logs',
 'accounts',
 'create',
 'datasource')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.RemoteUserMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/srv/webvirtcloud/accounts/views.py" in accounts
  103.             userattributes = user_edit.userattributes
File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/db/models/fields/related.py" in __get__
  480.                     self.related.get_accessor_name()

Exception Type: RelatedObjectDoesNotExist at /accounts/
Exception Value: User has no userattributes.

**Comment by catborise** [comment]
please checkout to get latest changes. it should be fixed.
