### ISSUE TITLE
After installing the latest new problems

### ISSUE THREAD

**Issue by ssbaksa** [retspen/webvirtcloud#161]
I hate to be the one to bring "bad news" but ...

1. There is missing lxml package in pip install requirements.
2. When I have added lxml new error was shown:

Environment:

Request Method: GET
Request URL: http://172.17.252.166:80/

Django Version: 1.8.11
Python Version: 2.7.12
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'computes',
 'console',
 'networks',
 'storages',
 'interfaces',
 'instances',
 'secrets',
 'logs',
 'accounts',
 'create',
 'datasource')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.RemoteUserMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  119.                 resolver_match = resolver.resolve(request.path_info)
File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py" in resolve
  365.             for pattern in self.url_patterns:
File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py" in url_patterns
  401.         patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py" in urlconf_module
  395.             self._urlconf_module = import_module(self.urlconf_name)
File "/usr/lib/python2.7/importlib/__init__.py" in import_module
  37.     __import__(name)
File "/srv/webvirtcloud/webvirtcloud/urls.py" in <module>
  17.     url(r'^accounts/', include('accounts.urls')),
File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/conf/urls/__init__.py" in include
  33.         urlconf_module = import_module(urlconf_module)
File "/usr/lib/python2.7/importlib/__init__.py" in import_module
  37.     __import__(name)
File "/srv/webvirtcloud/accounts/urls.py" in <module>
  7.     url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),

Exception Type: AttributeError at /
Exception Value: 'module' object has no attribute 'LoginView'

**Comment by Bandic007** [comment]
Yes I saw that. Currently working on that.
You can install lxml with:
pip install lxml

**Comment by ssbaksa** [comment]
True and I did that but then problem with view arises.
I am not able to found LoginView in django.contrib.auth module so ...

**Comment by Bandic007** [comment]
Can you try my build from here:
https://github.com/Bandic007/WebVirtCloud-B7

It should be working with latest fixes

**Comment by ssbaksa** [comment]
Hi bandic007,

It works now with your repo cloned.
Does that mean that ratspen is not working on webvirtcloud any more and
your repo is "the one"?

Bandic? HR? ZG? :-)

Lp

Sasa

**Comment by Bandic007** [comment]
BG actually, but it comes from Bandicoot - character from an old SEGA video game. Crash Bandicoot

**Comment by Bandic007** [comment]
@ssbaksa - actually @retspen merged my changes in his official repo so now the official one is also working with my latest fixes :)

**Comment by ssbaksa** [comment]
BG! Great. Bandić iz a surname of HR Capital city mayor so I assumed ... but  you know what they say about assumptions.

Thank you for great contributions and quick fixes.
I have one suggestion. When comes to sorting instances and compute nodes by name (by example), it would be better (to me looks more logical) to have sorted in a way that you sort 1. compute then under it sorted instances then 2. compute under it second compute instances etc.

Br

Sasa
