### ISSUE TITLE
instance clone Error: Instance mac '52:54:00:' invalid format!

### ISSUE THREAD

**Issue by honza801** [retspen/webvirtcloud#164]
bug by to @Bandic007 and @catborise 

Also - when I have a user, which is a staff one and "can clone VMs" and I hsare a template with him, when I try to clone the template from inside the user, I am getting this error:
Error: Instance mac '52:54:00:' invalid format!
I haven't change anything. I guess this issue (as I explained in another issue thread) is related to the "guess" mac function in the network card options. I am getting the same result when from the super admin user I use the guess option in the network settings and it gives me only '52:54:00:' mac every time. Also in options tab I don't have the possibility to change the network configs of course, because this is template shared by super admin, so I cannot do anything from that user practically.

Could you please try to fix this? I will try to help you with what I can!

**Comment by honza801** [comment]
@Bandic007 
fixed in commit 13ffaae522160505b75fcfdaea662df19318fda4 honza801/webvirtcloud fork

**Comment by Bandic007** [comment]
@honza801  - thank you very much! I've implemented the change in my installation and it works perfectly.
I've implemented it in my repo modified version also! 
I will be looking toward getting the users roles a little bit more flexible and fixing some other issues like the one that @catborise has with the sorting in instances page on super user.
Will you help with that also?
