### ISSUE TITLE
novnc spice problem

### ISSUE THREAD

**Issue by catborise** [retspen/webvirtcloud#168]
hi,

Only big problem with this project is related with novnc and spice console.
Keyboard problem and some undefined errors make it unusuable.
I wish to contribute that component but i have no clue where to start.
While i researching i get that information: qemu keyboard problem solved!! but that solution comes with 
"noVNC 1.0.0". can anybody integrate that? how to update info?

spice problem is different: console opens smoothly but there is no refresh. i am writing something to console. but it is now shown. then, i am connecting to virt-manager console, voala characters are there. 
So, keyboard is working but refreshing not working on spice? how to solve that?

does anybody encounter with that problem?

if you get response to keyboard some vm.. it show like that..
![image](https://user-images.githubusercontent.com/1725643/43629992-9b362a3a-9707-11e8-9e24-9a609f44ed38.png)

**Comment by catborise** [comment]
after some debug operation. Problem defined!
QXL display driver causes problems with spice. if you change it with vga or virtio problem will solve..

**Comment by Bandic007** [comment]
Cab you describe the process? Where do you change it or you will make a commit with this change included in you repo?

**Comment by Bandic007** [comment]
@catborise can you check the error I am getting with your lates repo changes aboute the vnc conaole and the rfb.js file? Please
