### ISSUE TITLE
Migrate from sqlite3.db to MySQL or MariaDB server? (maybe postgresql also)

### ISSUE THREAD

**Issue by Bandic007** [retspen/webvirtcloud#169]
@retspen  @catborise  @honza801 - can the application be modified to use some other SQL DB service apart from SQLite3? I want to use it with MariaDB 10 for example and have redundant DBs and replica tion in case of failure, etc.?

**Comment by catborise** [comment]
hi bandic db contains trivial information and too small for real db, i think.
but if it is "must" for you. changing database is very simple operation for django.

in settings.conf, there is a databases section. you can change it whatever you want.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

change to:
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'myproject',
        'USER': 'myprojectuser',
        'PASSWORD': 'password',
        'HOST': 'localhost',
        'PORT': '',
    }
}

for detailed explanation you can check;
https://www.digitalocean.com/community/tutorials/how-to-use-postgresql-with-your-django-application-on-ubuntu-14-04

for other examples google it...

**Comment by Bandic007** [comment]
Thank you!
