### ISSUE TITLE
VMs XMLs and storage feature request

### ISSUE THREAD

**Issue by Bandic007** [retspen/webvirtcloud#170]
This is not issue, it is a feature request.
@retspen  @honza801 @catborise - please, someone of you help to achieve this functionality:

Let's say that you have more than 2 compute hosts and shared storage where you keep disks. I have 8 + 3 compute nodes and HA storage. It would be great to have XML's of all machine created in one place and then you deploy it to desired compute node. That's way virtual machine will be first stored in WebvirtCloud and you can redeploy it as much as you wish especially now with cloud-enabled installations. It will be like OpenStack on much smaller scale.

**Comment by catborise** [comment]
i think you want to keep your xml files on shared storage. 
qemu-kvm standart mechanism says that they should stay in etc/libvirt/qemu. may be they change it in future releases but now it is that way. chancing qemu characteristic may be inappropriate... (me also want this feature for easiness, but as i say qemu...)

**Comment by ssbaksa** [comment]
You are right but not completely. You can't change qemu-kvm standart mechanism and that's not my point. Even OpenStack uses that for deployed machines. What you can keep in database is XML description/configuration file. Now you can migrate one machine from one compute node to another by exporting machine (and deleting it) from first one and importing that XML to destination compute node. If you can keep that definition file in database you can redeploy already created machine to any compute node and that's OpenStack way but in very, very complicated way. I have around 60 servers in Openstack cloud and it was necessary to know exact mechanism of creation and deployment. My problem is that I am Sysadmin and my programing skills are not polished so adding feature to WVC isn't my best option.
I will try to implement part of my idea trough command line python (or BASH script) program to show what can be benefit of it.

**Comment by honza801** [comment]
i use config management (puppet/salt/cfengine) to acomplish this. extending webvirtcloud to manage storage/network/etc, brings it closer to complex solutions such as openstack or opennebula, which i'm NOT a friend of. webvirtcloud does not offer IaaS but rather PaaS, and i'm very very happy with it.

**Comment by catborise** [comment]
i completely agree with you. i need a feature like that. my installation same as you. 
if any host crashed, instances xml's stay there and i cannot reach. because of that restore operation takes time.  for now, i keep xml backups on shared storage to restore easily. we can keep them on database but there are some considerations for realiability(activation of virtlock).

there is not any simple solution for iaas except webvirtcloud. proxmox/opennebula/openstack make it too complex.

**Comment by honza801** [comment]
again. you can use other tools to achive this. use any combination or all ot them of these:

* config management to store configuration
* shared replicated filesystem like nfs/gfs/glusterfs/afs
* do backups regullary

this solves all your problems (especially the config management)
