### ISSUE TITLE
Monitoring with Grafana

### ISSUE THREAD

**Issue by Bandic007** [retspen/webvirtcloud#171]
Hi @retspen @honza801 @catborise - please, someone of you to ask my questions:
 - The current sqlite3 db file contains the hosts, instances, users atributes and stuff like that as information. Can more stuff be added to be written in the database file - like to write the information and values from the instance Stats page for Real Time graphics and Logs and Compute Performance graphics into the DB?
 - where are the Graphics (for CPU, RAM, Traffic, etc) saved? In the system they are created live, but I was not able to find them in the sqlite3 DB, so I guess maybe they are not saved or they are saved in another place? Which is this place and if they are not saved - can we put those values also in the dabatase so that monitoring tools produce graphic from them also?
 - If it is in the DB, and the DB is changed by default to PostgreSQL support, it will be possible to monitor the system with Grafana. That is why I am asking.

**Comment by catborise** [comment]
hi bandic, as far as i know they do not save to anywhere. realtime stats shows only. 
webvirtcloud is web alternative for virt-manager and works like it.

as you say info get saved as RRD file format monitor them but there is an extension for libvirt to monitor guests. libvirt-snmp ? you can checkout .

**Comment by Bandic007** [comment]
Thank you!
