### ISSUE TITLE
VNC is not working over https

### ISSUE THREAD

**Issue by Bandic007** [retspen/webvirtcloud#173]
I am trying to get VNC working over https.
In my settings.py I have convigured:

`` ## WebVirtCloud settings

# Wobsock port
WS_PORT = 6080

# Websock host
WS_HOST = '0.0.0.0'

# Websock public port
WS_PUBLIC_HOST = 'my.domain.com' 

# Websock SSL connection
WS_CERT = '/etc/letsencrypt/live/my.domain.com/fulchain.pem'``

and in /console/novncd:

`CERT = DIR_PATH + '/etc/letsencrypt/live/my.domain.com/fulchain.pem'`

my.domain.com is just for illustration.
My ssl is fully working on the nginx server, however, when I try to open the vnc over https, I am getting 1006 erro all the time.
@catborise @honza801  - can you give me some advise or help with how to configure this?

![fail](https://user-images.githubusercontent.com/39150122/43994377-a7ab3cda-9da4-11e8-9e29-1ea8612b0667.png)

**Comment by Bandic007** [comment]
UPDATE: Actually it was never working fine on firefox.
Here is the log from Chrome - there it gives me connection time out error:
![rack](https://user-images.githubusercontent.com/39150122/43994719-72961564-9daa-11e8-8a7c-8f1cb8062cb3.png)

**Comment by Bandic007** [comment]
@honza801 @catborise 
I've made it work following the tutorial from this issue:
https://github.com/retspen/webvirtcloud/issues/126#issuecomment-394981688

Basically I've kept those settings I've posted above, but applied from this issue the proxying of the websockets over the nginx working port of the webvirtcloud. In my case port 443, not 80.
it is working now and I plan to make a patch which I will apply to my version of the repo in order to make this easy for other guys looking to make this work - either with or without ssl - proxying it over the nginx is a great idea!

**Comment by kilejiunderscorea** [comment]
Hello,

For those who still have the problem with novnc and https:
![image](https://user-images.githubusercontent.com/19324976/55147631-06cae980-5147-11e9-9a81-364b6ac6215d.png)

Try concatenating your cert file and key file into a pem file like this:
`$> cat cert.crt cert.key > cert.pem`

Then, in /etc/supervisord.conf at the include novncd part, make sure to add the cert parameter in command, like the image below:

![image](https://user-images.githubusercontent.com/19324976/55147932-95d80180-5147-11e9-91ef-f4ea5060e09b.png)

`$> systemctl restart supervisord`

And now, it should work fine.
![image](https://user-images.githubusercontent.com/19324976/55148134-f1a28a80-5147-11e9-828c-ad9e53721aa8.png)
