### ISSUE TITLE
Feature-Request: Staff users staring their own VMs

### ISSUE THREAD

**Issue by Bandic007** [retspen/webvirtcloud#182]
@catborise rise - is it too hard do add a logic decision to the start instance process. For example I exposed createing VM to my staff users, but I don't want they to see the actual compute nodes. So when they create a new VM and press the start button, I need some logic which can check the available compute nodes ram capacity for example and always start the VM to the one with more free resource.

**Comment by catborise** [comment]
scheduling mechanism is hard and webvirtcloud does not provide any feature which is not presented in libvirt. this mechanism is "Dynamic resource scheduler" in vmware and it needs solid migration mechanism.
but we can do some simple job to workaround. while creating(not starting) instance we can check all compute's resources and pick available one to create vm on that compute. is it a solution for you?

**Comment by Bandic007** [comment]
By the way @catborise  you can look at my modified repo yo check how I've exposed the vm creation for my staff users
