### ISSUE TITLE
can't console vnc

### ISSUE THREAD

**Issue by letran3691** [retspen/webvirtcloud#186]
Please help me.
i can't use console vnc " cannot concatenate 'str' and 'NoneType' objects"
![image](https://user-images.githubusercontent.com/19284401/45861396-8641bf80-bd96-11e8-8297-f9ebe0ca6ab8.png)

**Comment by catborise** [comment]
hi,
can you send output of "virsh dumpxml <vmname>".

**Comment by letran3691** [comment]
> hi,
> can you send output of "virsh dumpxml ".

please help me.
this is dumpxml a vm 
https://paste.ofcode.org/cTZH4VkcNPz7uw9NcEtCC6

**Comment by catborise** [comment]
vnc console missing in your vm definition

there should be a device like below under devices

<graphics type='vnc' port='-1' autoport='yes' listen='0.0.0.0'>
  <listen type='address' address='0.0.0.0'/>
</graphics>
<video>
  <model type='vga' vram='9216' heads='1'/>
  <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
</video>

you create a vm with a serial console only.

**Comment by catborise** [comment]
you can close the issue

thanks
