### ISSUE TITLE
difference of console spice lite vs full

### ISSUE THREAD

**Issue by honza801** [retspen/webvirtcloud#188]
hi @catborise,

can you please explain the differences of console spice lite vs full. i tried to open both of them, buti can't see any difference. there were some differences (panel on the left) some weeks ago, but these are now gone.

thanks
jan

**Comment by catborise** [comment]
hi,
there is not any difference for spice full/lite console for now.
but if console is vnc. there are some differences which are some functions. clipboard, ekstra keys. console sharing etc.
left panel thing is belong to vnc full console...

**Comment by honza801** [comment]
aaaha. i see, thanks :)
