### ISSUE TITLE
wrong hypervisor detection

### ISSUE THREAD

**Issue by honza801** [retspen/webvirtcloud#194]
hi @catborise 

we' ve got installed more hypervisors on one compute node (qemu-system-aarch64 qemu-system-arm      qemu-system-i386 qemu-system-x86_64). now instances.views.instance ends with:

Error: invalid argument: architecture from emulator 'armv7l' doesn't match given architecture 'x86_64'

problem comes with commit f477dd6a11632b55125d107fd4e0dc750ac0c80f 

please review it.

thanks
jan

**Comment by catborise** [comment]
@honza801 could you send me output of "virsh capabilities" and "virsh domcapabilities"

**Comment by honza801** [comment]
sure.
[capabilities.txt](https://github.com/retspen/webvirtcloud/files/2437143/capabilities.txt)

**Comment by catborise** [comment]
@honza801 hi honza, it is fixed.
but problem is rooted with vm creation.
we should choose machine types. for example:
click create instance -> choose emulation(x86, x86_64, armv7I, aarch64) -> choose machine type(pc,q35), then populate info. finally create image.

i should implement that. with a wizard it could be easy.

**Comment by catborise** [comment]
for now, we can only create x86_64 arch, and latest machine emulation (pc= pc-i440fx-rhel7.5.0, or pc = pc-i440fx-xenial(for ubuntu16.04)) type machines. if you want to create arm machine you cannot.

with a instance create wizard, it could be possible another type of machine...

**Comment by honza801** [comment]
i don't want to create bizzare architectures with webvirtcloud :) we play with arm from the command line. the problem was, that installed binary on the compute node broke the cloud. hope it is fixed now.

thanks
fous

**Comment by honza801** [comment]
@catborise 
just one more comment. if you are doing some fix, please create another branch for it on the top of retspen/master.

in this case i have to do cherry pick. which is discouraged, because it actually generates new commit (and its id). this results in same commits with different id in the repo tree.

i know it is slowing developer down, but the commit history stays clean and nice :)

if you are interested and want to repair this, let me know, i can explain the procedure.
