### ISSUE TITLE
feature request: change color of expanded "create instance" button type

### ISSUE THREAD

**Issue by Bandic007** [retspen/webvirtcloud#199]
@catborise @honza801 
You know when you hit the green + button on the Instance page and choose a compute host, you are being dropped in the create new instance page.
On the top there are 3 buttons - Custom, Template and XML. When you click on some of those buttons, the are actually expanding, but nothing is suggesting that you can click back on the same button and collapse the fill-in form which was opened.
The collapsed button color is green - can you make it when you click on some button and it is in expanded state, this button to become red, so that it can suggest to click you back to exit from this particular form?
It would be great, thanks!
In those example pictures below, I've opened the Custom button, but nothing suggests it is exactly it which is opened.
![image](https://user-images.githubusercontent.com/39150122/47239871-2d923080-d3ef-11e8-9a99-b902f417e3d4.png)
![image](https://user-images.githubusercontent.com/39150122/47239906-4a2e6880-d3ef-11e8-82f3-2145b68fb650.png)

**Comment by catborise** [comment]
i dont know very well javascript but i can convert it to accordion which opens only one at a time...

**Comment by Bandic007** [comment]
yes this can help. Can you make such change in some branch so that I can give it a try and see if it is good enough to use it please?

**Comment by Bandic007** [comment]
or maybe @honza801 can help with the java?

**Comment by honza801** [comment]
hmm, maybe there should be tabs, not collapsed divs... ?

**Comment by Bandic007** [comment]
I personally think tabs will be the best solution. I just suggested something I thought will be simple.
