### ISSUE TITLE
Default Password

### ISSUE THREAD

**Issue by thiagocpv** [retspen/webvirtcloud#2]
Hi,

the default user/password doesn't work. How can I reset it?

Thanks.

**Comment by retspen** [comment]
Hello,

Default credentials has broken in Django 1.8, you need create user manually

```bash
$ python manage.py createsuperuser
```

**Comment by thiagocpv** [comment]
Ok, I did it and working fine, thanks.

The project is half with webvirtmgr? Because they looks similar and one has
some extras features and the other doesn't.
Em 22/04/2015 02:47, "Anatoliy Guskov" <notifications@github.com> escreveu:

**Comment by retspen** [comment]
Fixed - 981eb65fac68d73e0e90e0625ba581e6f54c629f
