### ISSUE TITLE
Problem connecting via local socket

### ISSUE THREAD

**Issue by deliciousfudge** [retspen/webvirtcloud#20]
I've installed webvirtcloud onto a machine as per the instructions in the readme. The machine already has a few KVM machines set up, so I'm able to run something like this without issue:
```
$ virsh list

Id    Name                           State
----------------------------------------------------
 2     Some VM                     running
```

However, after adding a local socket entry on the computes tab of webvirtcloud, I get the following on the instances tab:
```
Error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Permission denied
```
I've tried adding both my local and the www-data user accounts to the libvirtd group but I still get the same error. 

Any ideas?

**Comment by retspen** [comment]
```bash
$ sudo adduser www-data kvm
```

**Comment by deliciousfudge** [comment]
Thanks. Tried that but still getting the same error message.

I'm able to use TCP at the moment, so this isn't a huge deal. Would still be nice to solve though.

**Comment by retspen** [comment]
After that need restart service nginx

**Comment by deliciousfudge** [comment]
```
sudo service nginx restart
```
Refreshed the page but still getting the same error, even after clearing the cache.

**Comment by retspen** [comment]
Can you add libvirtd group to www-data and then restart service nginx?

**Comment by deliciousfudge** [comment]
```
sudo adduser www-data libvirtd
sudo service nginx restart
```
No change unfortunately

**Comment by retspen** [comment]
Can you reboot your server? Now I tested the Issue and my configuration work perfectly.

**Comment by deliciousfudge** [comment]
Not able to right now but will give it a try later on and report back. Thanks for the help :)

**Comment by deliciousfudge** [comment]
Apologies for the delay @retspen.

I rebooted and the issue was resolved. Not quite sure what happened but all good now, so I'll close this up.
