### ISSUE TITLE
Resize RAM  when VM runing

### ISSUE THREAD

**Issue by letran3691** [retspen/webvirtcloud#203]
I want Resize RAM a VM when it running. Must change where?
I did fix a paragraph code, can Resize. but it's not apply when running, must shutdown it applies
version old I fix success. after update version I can't fix it's :(

![image](https://user-images.githubusercontent.com/19284401/48124537-27d19180-e2af-11e8-978b-3d62a64a320e.png)

**Comment by catborise** [comment]
you cannot change maximum allocation of memory while running.
but you should change current allocation of memory while instance is running.

which one you cannot change?

**Comment by letran3691** [comment]
I can't change any option at tab #RESIZE while VM running.  when just shutdown VM, changes apply to VM

**Comment by catborise** [comment]
i can work it on. but i need time..

**Comment by letran3691** [comment]
When VM shutdown. I set  "Current allocation (MB) 2G"  and "Maximum allocation (MB) 8G "
![image](https://user-images.githubusercontent.com/19284401/48240706-5910a580-e406-11e8-8479-3f5f659312f1.png)

 But when I run VM then part "Current allocation  " auto received "Maximum allocation  8G"
![image](https://user-images.githubusercontent.com/19284401/48240749-8a897100-e406-11e8-954d-c78d8f56afaf.png)

I don't know bug where

**Comment by catborise** [comment]
i think it is default behaviour of KVM guests. While vm is starting it set maxiumu allocation. After boot up of instance, memory ballooning mechanism activates. Then if it is possible, it shrinks to current allocation.

to sum up, there is not any bug. but it is a feature :)

**Comment by letran3691** [comment]
Yes. I check again and accurate  as you say. But i can't  #resize current memory while VM running. I did test Increase RAM while VM running with command "virsh setmem php-fpm_test 2049M --live",  it's works normally.
Please help me can #resize while VM running. Please!!!

**Comment by catborise** [comment]
hi @letran3691 i add online resize for memory, it appears to work. it is now on branch. but after some test i will merge it to master. [link](https://github.com/catborise/webvirtcloud/commit/44d73cc780bc1e5a5fef213c0b54536fab6c05a7)

**Comment by letran3691** [comment]
thank you very much. but i have change  a paragraph code file instance.html 

[https://github.com/catborise/webvirtcloud/commit/44d73cc780bc1e5a5fef213c0b54536fab6c05a7#r31376128](url)

**Comment by letran3691** [comment]
[](url)
