### ISSUE TITLE
request.user.is_superuser or request.user.is_staff or not userinstance.is_template

### ISSUE THREAD

**Issue by catborise** [retspen/webvirtcloud#204]
hi @honza801

i am not sure i think there is  logic error. can you please check it. i do not want to break logic.

`{% if media_iso and request.user.is_superuser or request.user.is_staff or not userinstance.is_template %}`
          (instance.html)                                                      

there is not any media_iso but you could call mount_iso function with 'none' value. It causes error

thanks

**Comment by honza801** [comment]
hmm, django templates cannot use parenthesis in conditionals... i had to put it into view :(

check latest commit in master branch
https://github.com/honza801/webvirtcloud/commit/3d43aa392c009a1b81fe8995459e4b989a8f24bb

fous

**Comment by catborise** [comment]
thanks. it works.
