### ISSUE TITLE
local variable 'disk_cache' referenced before assignment

### ISSUE THREAD

**Issue by Bandic007** [retspen/webvirtcloud#215]
@catborise - after the latest commit to your own webvirctloud repo, I am getting this when I try to open running VM:

Request Method: | GET
-- | --
http://rack.bigspace.top:443/instances/1/Ubuntu_web/
1.11.18
UnboundLocalError
local variable 'disk_cache' referenced before assignment
/srv/webvirtcloud/vrtManager/instance.py in disks, line 280
/srv/webvirtcloud/venv/bin/python2
2.7.15
['/srv/webvirtcloud',  '/srv/webvirtcloud/venv/bin',  '/srv/webvirtcloud/venv/lib/python2.7',  '/srv/webvirtcloud/venv/lib/python2.7/plat-x86_64-linux-gnu',  '/srv/webvirtcloud/venv/lib/python2.7/lib-tk',  '/srv/webvirtcloud/venv/lib/python2.7/lib-old',  '/srv/webvirtcloud/venv/lib/python2.7/lib-dynload',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/srv/webvirtcloud/venv/local/lib/python2.7/site-packages',  '/srv/webvirtcloud/venv/lib/python2.7/site-packages']
Thu, 10 Jan 2019 14:05:05 +0000

**Comment by Bandic007** [comment]
I think I've found the issue:
line 251 in vrtManager/instace.py

disk_format = used_size = disk_size = None

should include 'disk_cache' also, cause in my case some drives does not have cache, but it cannot give me cache: none and it crashes.
I've fixed this locally, but you may want to fix it there.

**Comment by catborise** [comment]
Thanks bandic i will fix. You are right.

**Comment by Bandic007** [comment]
Fixed! Thanks!
