### ISSUE TITLE
Feature request: ability to add static addresses from web interface

### ISSUE THREAD

**Issue by Bandic007** [retspen/webvirtcloud#217]
@catborise - can you make it possible to add several things from the web interface, in the network settings in the Compute:
 - edit the network details (not only on creation, but also when the network is stopped)
 - choose start and end IP addresses for the subnet
 - add / remove / change static assigned IP addresses (for example add a green + button in the static addresses section)

The features I am speaking about should be place in this section:
![image](https://user-images.githubusercontent.com/39150122/51321212-ddb51b00-1a6a-11e9-8bc7-8dbb757fe457.png)

Thank you!

**Comment by catborise** [comment]
hi bandic, i have some news :)
it is ready 
adding deleting editin fixed address functionality is added.
changing dhcp range for stopped network is added

checkout my repo. test and feedback to pull it to retspen
