### ISSUE TITLE
Network devices - NIC can't be changed for existing machine

### ISSUE THREAD

**Issue by ssbaksa** [retspen/webvirtcloud#221]
When I try to change NIC assignment for for existing machine, after clicking Change button value of NIC field remain the same. Only change that works is changing that value in XML. This is tested with latest Catborise release.
![network page](https://user-images.githubusercontent.com/19958704/51734876-1fa31a00-2086-11e9-8d5c-a5e29102a510.JPG)

**Comment by Bandic007** [comment]
@catborise - I can confirm this issue. I am observing the same behavior.

**Comment by Bandic007** [comment]
@catborise - it seems fixed now! Thank you!
Can you take a look at my last comment here also:
https://github.com/retspen/webvirtcloud/pull/220

Thank you!

**Comment by Bandic007** [comment]
@ssbaksa - close the issue

**Comment by ssbaksa** [comment]
Fixed & closed
