### ISSUE TITLE
Feature request: Grouped instances page - collapsed by default

### ISSUE THREAD

**Issue by Bandic007** [retspen/webvirtcloud#222]
@catborise - in a scenario, when there are several computes, I would like to have an option to choose a collapsed by default grouped instances page - again choosable from the settings.py, like the grouped and non-grouped variants. I would like this, because when I have 5-6 compute hosts added to webvirtcloud and I have 5-10 VM Instances on every single of them, I have to scroll down and the default instances screen looks overlapped with information and difficult to navigate trough all those instances without confusions some times. A variant of the instances page collapsed by default will allow me to choose a host and look only at his instances expanded. No other features ar needed - just collapsed by default compute hosts. 
Can you make this possible?
Thank you!

P.S. - I know that you can collapse all, by clicking on the "#" icon on the top row, but it will feel more nicer if when I log in, they are collapsed by default. :)

**Comment by catborise** [comment]
hi bandic, Actually there is nothing collapsed only hide table rows. May be we call hide script. i could not add the choice for that option. it affects other things

you can add this script to alinstances.html

$( document ).ready(function() {
    hide_all_host_instances();
 });

**Comment by Bandic007** [comment]
@catborise  - thank you! It is working more than fine!
