### ISSUE TITLE
webvirtcloud on Debian 10 (Buster) - IPTables glitch...

### ISSUE THREAD

**Issue by 4920441** [retspen/webvirtcloud#233]
Hi,
after a couple of minutes I installed everything on my test host. The 'admin' accound led into some funny errors, but a newly generated 'superuser' account  seems to fix all the auth problems whatsovever....

Generating and editing a guest is now possible, but I am not able to start any virtual network device, because of this error:

Error: internal error: Failed to apply firewall rules /sbin/iptables --table filter --insert INPUT --in-interface virbr0 --protocol tcp --destination-port 67 --jump ACCEPT: iptables v1.8.2 (nf_tables): CHAIN_ADD failed (No such file or directory): chain INPUT

Any hints?  

I am also nut sure what is meant by "no such file or directroy"? iptables is accessible .

Cheers,

**Comment by catborise** [comment]
Hi, i think it is not related with webvirtcloud. It could be  a bug related with libvirt + iptables

What is your libvirt version(virsh version)

Could you try this command on host. What is the output?
Virsh net-start default

**Comment by 4920441** [comment]
Hi, 
thanks for the hint..., do you have a solution anyway? Its the default debian buster deb package...:

virsh version
Compiled against library: libvirt 5.0.0
Using library: libvirt 5.0.0
Using API: QEMU 5.0.0
Running hypervisor: QEMU 3.1.0


virsh net-start default
error: Failed to start network default
error: internal error: Failed to apply firewall rules /sbin/iptables --table filter --insert INPUT --in-interface virbr0 --protocol tcp --destination-port 67 --jump ACCEPT: iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain INPUT

**Comment by 4920441** [comment]
For Anyone who has a similiar Problem, 

On Debian (10) by default the nf_tables backend is used instead of the xtables backend.

That does not work too well in his constellation, you can back to the old backend by 

update-alternatives --set iptables /usr/sbin/iptables-legacy

Cheers,

4920441
