### ISSUE TITLE
Update using git pull - Error

### ISSUE THREAD

**Issue by thiagocpv** [retspen/webvirtcloud#24]
Hi there!

I'm getting this error when I ran git pull....

Updating b8caf3f..7c5b606
error: Your local changes to the following files would be overwritten by merge:
        webvirtcloud/settings.py
Please, commit your changes or stash them before you can merge.
Aborting

My settings.py was modified by myself with cert files, IP, etc.

Need I update this file? Is very important?

Thanks.

**Comment by retspen** [comment]
Copy your settings, update and then restore. Thats update have a bit fix.

**Comment by thiagocpv** [comment]
All right, that's done.

Thanks.
