### ISSUE TITLE
Error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Permission denied 

### ISSUE THREAD

**Issue by TurboCheetah** [retspen/webvirtcloud#240]
I have just installed it and have not changed anything. I added a compute node and then got this error. I added myself to the libvirt group and virt-manager works just fine. Only Webvirtcloud has this issue. Help?

**Comment by catborise** [comment]
where did you install webvirtcloud? 
on kvm host or a vm instance?
how which protocol did you use while adding host(ssh, tcp, ...)

![image](https://user-images.githubusercontent.com/1725643/59194322-54c18c00-8b91-11e9-91ec-1d16b8615dec.png)

**Comment by shinebayar-g** [comment]
After fresh install on ubuntu 18.04 I've got the same issue after adding compute machine by selecting **local** option. What should I do?

**Comment by catborise** [comment]
Have you run that script on the host?
wget -O - https://clck.ru/9V9fH | sudo sh
Before you run that script you can look what is it. What configs have it.

What is the error while creating instance?

**Comment by shinebayar-g** [comment]
Yes  I've run the script. But I guess I mixed up users. I initially started process as sudo user and then run that script as root user. I guess these fucked up my installation. Recreating fresh VPS again.

**Comment by catborise** [comment]
I recommend you that isolate webvirtcloud from hypervisor host.
How;
1. If you want to manage more than one host, you can create a vm and install webvirtcloud on it.
2. If you do not want to reserve a vm for webvirtcloud. You could use containers. Docker installation is simple as dead. 
So that your users and other Configurations do not mixed up.

**Comment by shinebayar-g** [comment]
I see thank you very much for your suggestion. Right now this is my first try of webvirtcloud. So I'm just testing things out. Once I get familiar with the project concepts I'll create dedicated host for webvirtcloud :)

Also I'll try to enhance docs here and there If I see something broken.

**Comment by shinebayar-g** [comment]
Okay, just finished installing. I'm still seeing this error. Here is my whole installation steps.

```
sudo apt-get update
sudo apt-get -y install git virtualenv python-virtualenv python-dev python-lxml libvirt-dev zlib1g-dev libxslt1-dev nginx supervisor libsasl2-modules gcc pkg-config python-guestfs
git clone https://github.com/retspen/webvirtcloud
cd webvirtcloud
cp webvirtcloud/settings.py.template webvirtcloud/settings.py
python # Generating secret key in python shell
vim webvirtcloud/settings.py # putting the key here
sudo cp conf/supervisor/webvirtcloud.conf /etc/supervisor/conf.d
sudo cp conf/nginx/webvirtcloud.conf /etc/nginx/conf.d
cd ..
sudo mv webvirtcloud /srv
sudo chown -R www-data:www-data /srv/webvirtcloud
cd /srv/webvirtcloud
virtualenv venv # This line gave error, because folder was owned by www-data:www-data now
sudo chown -R me:me venv # So I had to change back permission to my current user
pip install -r conf/requirements.txt
python manage.py migrate
sudo chown -R www-data:www-data /srv/webvirtcloud # fixing permissions back after installing things
sudo rm /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo service supervisor restart
wget -O - https://clck.ru/9V9fH | sudo sh
```

Now I'm here.

![image](https://user-images.githubusercontent.com/3091558/68324215-e19d5100-0101-11ea-8143-99533ffbb362.png)

![image](https://user-images.githubusercontent.com/3091558/68324181-d2b69e80-0101-11ea-875c-ab603541818f.png)

I guess I followed everything correctly, are you seeing anything abnormal here?

**Comment by catborise** [comment]
Hmm, i never try local connection. I should ...
Have you install virt-manager? Can you run it to check if libvirt service is working. This problem seems to libvirt service problem.

**Comment by shinebayar-g** [comment]
I didn't install virt-manager. I guess it wasn't needed.

```

**Comment by catborise** [comment]
Virt-manager does not need. But to check somethings, it is useful.
Please run on the host:
virsh list

**Comment by shinebayar-g** [comment]
Ran command as my current user

```sh
$ virsh list
error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Permission denied
```

**Comment by catborise** [comment]
As you see it is related with users and permissions.
This link mention that permission problem, could you look:
http://thelinuxerrors.blogspot.com/2012/10/failed-to-connect-socket-to.html

**Comment by shinebayar-g** [comment]
It is indeed. Who should own this file?

**Comment by shinebayar-g** [comment]
Now I'm seeing this error. How can I add storage?

![image](https://user-images.githubusercontent.com/3091558/68326330-2d51f980-0106-11ea-823e-f5792123a6a3.png)

**Comment by catborise** [comment]
Libvirt-sock problem Seems to solved.
Latest one is not related with that problem.
—-
You should create a storage pool on the host.
Go to computes.
Storages, create a pool which will contain disk images.

**Comment by shinebayar-g** [comment]
Just double checked it by removing `www-data` user from `libvirt` group again. Error was caused by this indeed. I'll make PR changes to document these things.

Oh thank you! I didn't know I actually had to click on the compute name. Now I'm seeing whole lot of menus out there! Thank you very much.

/close
