### ISSUE TITLE
Aftere Debian Upgrade:  Error: authentication unavailable: no polkit agent available to authenticate action 'org.libvirt.unix.manage'

### ISSUE THREAD

**Issue by 4920441** [retspen/webvirtcloud#250]
Hi,

after upgrading from debian 9 to debian 10 I get the following error after logging in to webvirtcloud

Error: authentication unavailable: no polkit agent available to authenticate action 'org.libvirt.unix.manage'

The funny thing is, the polkit daemon is running fine elsewhere, it seesm.

18585 ?        Ssl    0:00 /usr/lib/policykit-1/polkitd --no-debug

my virsh commands work also fine... (executed as root)

What could have happend, so webvirtcloud does not see a polkit agent?

Thanks for your help!

Cheers,

**Comment by 4920441** [comment]
https://github.com/retspen/webvirtcloud/issues/210

Don't know why that happened after upgrade but the Posting above temporarily fixes it... so I can search for the cause without not having webvirt running...:-)

**Comment by ycsos** [comment]
you should add your user into group libvirt, like:  sudo usermod -a -G libvirt www-data
