### ISSUE TITLE
webvirtcloud and webvirtmgr

### ISSUE THREAD

**Issue by TerenceLiu98** [retspen/webvirtcloud#251]
Can we migrate from WebVirtMgr or can we store this two repo in one enviorment?

 I had set up the WebVirtMgr, however when I installed the WebVirCloud I found that it cannot `runserver` properly with an error: `ImproperlyConfigured: The SECRET_KEY setting must not be empty.`

**Comment by TerenceLiu98** [comment]
also, what is "internal error: failed to get number of host interfaces: unspecified error - errors in loading some config files" ?
looking forward to reply

**Comment by catborise** [comment]
you can use both of them at the same time. but you should install them different env. for example docker or different vm. webvirtmgr and webvirtcloud apps are different. no need to migrate. only add hosts

ImproperlyConfigured: The SECRET_KEY setting must not be empty. : you can find necessary steps on readme. you must generate a secret key.

"internal error: failed to get number of host interfaces: unspecified error - errors in loading some config files": what is your libvirt version on host?

**Comment by TerenceLiu98** [comment]
Yes, I ran `mgr` and `cloud` in different physical machine. I will check the version of libvirt

**Comment by TerenceLiu98** [comment]
@catborise hi! The version of libvirt I am using is 4.0.0

**Comment by catborise** [comment]
@TerenceLiu98 as far i understand, it is related with libvirt configuration problem. it is not related with webvirtcloud or webvirtmgr.
you can check it with on hosts: "virsh iface-list", to see if there is a config error or not and check the libvirt logs/deamon.

can you describe your network config for your instances?

**Comment by TerenceLiu98** [comment]
@catborise it returns error:
```
error: Failed to list interfaces
error: internal error: failed to get number of host interfaces: unspecified error - errors in loading some config files
```

**Comment by catborise** [comment]
> @catborise it returns error:
> 
> ```
> error: Failed to list interfaces
> error: internal error: failed to get number of host interfaces: unspecified error - errors in loading some config files
> ```

there are some config error in network interfaces on host. i think you are using ubuntu. you should check network configuration

**Comment by TerenceLiu98** [comment]
@catborise you're right. the version is ubuntu 18.04 LTS. I am using netplan and set up a net bridge.
