### ISSUE TITLE
Feature change request

### ISSUE THREAD

**Issue by lord-kyron** [retspen/webvirtcloud#252]
Hi @catborise 
Can you please make some small changes, which looks logical to me and will make it easier for the user.
1. Change the order of volume disk space displayed from total/used to used / from total.
Example:
![image](https://user-images.githubusercontent.com/39150122/64947084-eb7ea280-d87c-11e9-8e25-add56d3f487b.png)
2. Change the RAM Utilization values for either Computes and Instances - when the RAM value goes over 1024 MB, to be shown as GB values instead of MB as the values are pretty big there.
Example:
![image](https://user-images.githubusercontent.com/39150122/64947209-300a3e00-d87d-11e9-9615-70b82842194d.png)
3. Possibility to upload and download(export) instances XML files from the Instance -> Settings -> XML tab. It will be very helpful if the XMl config can be directly downloaded (exported) and uploaded (for uploading changed or new configs).
Example:
![image](https://user-images.githubusercontent.com/39150122/64947481-bf175600-d87d-11e9-840e-35f95f7a3bee.png)

Please, tell me your opinion and if this is possible!
Thank you!

**Comment by catborise** [comment]
@lord-kyron i am not sure for request 2 but others are possible. We can do it. Thanks
