### ISSUE TITLE
Feature request - hot add cpu and mem

### ISSUE THREAD

**Issue by lord-kyron** [retspen/webvirtcloud#261]
@catborise - I saw that the commands to live add more CPU cores or increase the memory of the VM are pretty simple. Can you please, make available the possibility to add more CPU and RAM to the VMs live trough the web interface? It will be very helpful to do those when we need to increase VM resources, instead of shutting down the VM.

The requested options to make possible are:
 - hot add CPU 
 - hot remove CPU
 - hot add RAM

references, where I saw this is possible:
CPU - https://www.unixarena.com/2015/12/linux-kvm-how-to-add-remove-vcpu-to-guest-on-fly.html/
RAM - https://earlruby.org/2014/05/increase-a-vms-available-memory-with-virsh/

Thank you!

**Comment by catborise** [comment]
hot memory adding already implemented. I did activate it. But you know that you cannot change maximum memory allocation online. But only current allocation.

hot cpu adding requires some steps. Firstofall cpus must be hotpluggable. Then you can add or remove only current ones, again not maximum cpus.
i can implement it but it requires time.
@lord-kyron 
thanks
