### ISSUE TITLE
Full VNC console on half screen

### ISSUE THREAD

**Issue by lord-kyron** [retspen/webvirtcloud#262]
@catborise - I have a problem since some of the last builds (not sure which commit caused it), but when I try to use the full VNC console, half of the displayed page is taken by the navigation menu and only half of the page is for the console.
This was not like this before and I assume it is not what is expected. Here is a screenshot of the issue:
![image](https://user-images.githubusercontent.com/39150122/69129896-1a510900-0ab8-11ea-912a-f12207056a9e.png)
As you can see the navigation bar is taking the half of the screen and there are options to collapse/expand it visible.
Please, fix this if possible!
Thanks!

**Comment by catborise** [comment]
yea there is some problem full vnc. thanks. i will handle it.

**Comment by catborise** [comment]
@lord-kyron it solved. thanks for feedback
for now, on my repo.

**Comment by lord-kyron** [comment]
Thanks it is working now! You can make a pull request to merge it to the main repo!
