### ISSUE TITLE
VM IP Address exposed on the Instances page

### ISSUE THREAD

**Issue by lord-kyron** [retspen/webvirtcloud#277]
Hi @catborise 
I am using your latest implementation in which I can see the VM IP address using the qemu agent in the VM settings - network settings page.
However, I feel it will be so much easier this same IP address to be exposed and shown also on the main Instance page right after the VM name (between VM name and user columns)
This will make it easier to see all VMs IPs at one place and get the one you need.
Also, it will be good only the primary (only one - the first NIC IP address) to be shown top avoid many IP s and lines on the same VM. I will be useful this IP shown on the Instance page to be clickable also and to take you the Network settings of the VM, which the IP belongs to.

Hope you understand me!
Thanks!

**Comment by catborise** [comment]
Show ip address on some restricted areas is a problem. i do not know how to handle some different scenarios.
1. An instance may have many interfaces.
2. An interface does not have any address.
3. An interface has only ipv4 address
4. An interface has many ipv4 address
5. An interface has only ipv6 addresss
6. An interface has both ipv6 and ipv4 address
7. An interface has many ipv4 address and ipv6 address

Showing one of the ip address on the instances pages could be exahusted/may cause some delay. They can be store in db but refreshing needed...

we need a strategy....
