### ISSUE TITLE
Cannot resize memory from web gui 

### ISSUE THREAD

**Issue by james-watson-oxb** [retspen/webvirtcloud#281]
When I attempt to change the memory size from the web gui I get the following error: 

[error] 20973#20973: *6510 open() "/srv/webvirtcloud/static/js/worker-xml.js" failed (2: No such file or directory) client: 1.1.1.1, server: , request: "GET /static/js/worker-xml.js HTTP/1.1", host: "11.1.12.1:8020"

I have the last git pull and this is new installation running on Ubuntu 18.04 

Please advise how to solve. I do not see worker-xml in the git pull, do I need to update any names in the code ? 

root@k1:~# ls /srv/webvirtcloud/static/js/
ace.js  bootstrap.min.js  bootstrap-multiselect.js  Chart.bundle.min.js  ext-textarea.js  jquery.js  js.cookie.js  mode-xml.js  novnc  plugins  sortable.min.js  spice-html5

**Comment by catborise** [comment]
worker-xml.js is a trivial error. it does not effect the app. 
Is vm running while resizing ?
Only Current allocation could be changed if it is running.

**Comment by james-watson-oxb** [comment]
Yes the VM is running. I click Resize and the web is then redirected back to the resize page and the values do not change. The only error in the logs is the one above so I thought it maybe the cause. How else can i troubleshoot this issue ? any debug options available ?

**Comment by catborise** [comment]
It is working without feedback. It will be good if i add feedback message.
as i said, while it is running you can change only "Current allocation", but not "Maximum allocation".
you can check it if it is working:
instance details -> settings -> XML
check xml to see if there is a tag like:
<memory unit='KiB'></memory>
  <currentMemory unit='KiB'></currentMemory>
if memory and current memory values are different, then it is working.

what is the guest os(instance os)? windows or linux?
