### ISSUE TITLE
ImportError: cannot import name VIR_DOMAIN_UNDEFINE_KEEP_NVRAM

### ISSUE THREAD

**Issue by ssbaksa** [retspen/webvirtcloud#282]
After pulling latest version this error occure:

File "/srv/webvirtcloud/instances/views.py", line 25, in <module>
    from libvirt import libvirtError, VIR_DOMAIN_XML_SECURE, VIR_DOMAIN_UNDEFINE_KEEP_NVRAM, VIR_DOMAIN_UNDEFINE_NVRAM
ImportError: cannot import name VIR_DOMAIN_UNDEFINE_KEEP_NVRAM

I can't find VIR_DOMAIN_UNDEFINE_KEEP_NVRAM defined in libvirt module which is pulled by pip (latest requirements file).

By removing offending import part, I am able again to migrate/start application

**Comment by catborise** [comment]
which version of qemu and libvirt are you using on host?

**Comment by ssbaksa** [comment]
System is Ubuntu 16.04.6 upgraded to latest.

libvirt-bin                           1.3.1-1ubuntu10.27      amd64
libvirt-dev:amd64                     1.3.1-1ubuntu10.27      amd64
libvirt0:amd64                        1.3.1-1ubuntu10.27      amd64

qemu-kvm                              1:2.5+dfsg-5ubuntu10.42 amd64

Python libvirt version:
Metadata-Version: 2.1
Name: libvirt-python
Version: 5.10.0

**Comment by catborise** [comment]
host libvirt is too old on ubuntu. can you upgrade it?

**Comment by ssbaksa** [comment]
This is the latest one for Ubuntu 16.04.6. As those are production servers I can't simply upgrade to 18.04 but I will try to evacuate all from one server which is not under to much load and upgrade it to 18.04. It must be LTS version. Report will follow.

**Comment by ssbaksa** [comment]
Well, now I have another problem. 18.04 and python. Lets see how to fix that.

root@suncica8:/srv/webvirtcloud# virtualenv venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /srv/webvirtcloud/venv/bin/python2
Not overwriting existing python script /srv/webvirtcloud/venv/bin/python (you must use /srv/webvirtcloud/venv/bin/python2)
Installing setuptools, pkg_resources, pip, wheel...
  Complete output from command /srv/webvirtcloud/venv/bin/python2 - setuptools pkg_resources pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py", line 24, in <module>
ImportError: cannot import name DependencyWarning

**Comment by catborise** [comment]
can you tell me how do you install webvirtcloud? on host, or on a guest.
I recommend you use docker. it is simple and neat. i update doc for docker installation. pls look up "wiki".

it is needed to update only host not webvirtcloud.(you dont have to install webvirtcloud on host)

**Comment by ssbaksa** [comment]
Yes, I see your point. I must admit that I really hate docker (I don't have proper reason but somehow I don't like it) but I can install it on independent server with Ubuntu 16.04 which I will not update to 18.04 in the near future.

I have installed WebvirtCloud on host, actually on few hosts for redundancy reasons.

**Comment by ssbaksa** [comment]
On completely new server without any virtualization i get this after 
pip install -r conf/requirements.txt
python manage.py migrate

Installing collected packages: pytz, Django, numpy, websockify, gunicorn, lxml, libvirt-python, rwlock
Successfully installed Django-1.11.26 gunicorn-19.9.0 libvirt-python-5.10.0 lxml-4.4.2 numpy-1.16.6 pytz-2019.3 rwlock-0.0.7 websockify-0.9.0
(venv) root@backup:/srv/webvirtcloud# python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/webvirtcloud/webvirtcloud/urls.py", line 3, in <module>
    from instances.views import index
  File "/srv/webvirtcloud/instances/views.py", line 25, in <module>
    from libvirt import libvirtError, VIR_DOMAIN_XML_SECURE, VIR_DOMAIN_UNDEFINE_KEEP_NVRAM, VIR_DOMAIN_UNDEFINE_NVRAM
ImportError: cannot import name VIR_DOMAIN_UNDEFINE_KEEP_NVRAM

**Comment by catborise** [comment]
it is meaningless, VIR_DOMAIN_UNDEFINE_KEEP_NVRAM is in libvirt-python and it is 5.10. 
but as far as i see webvirtcloud wants "libvirt" on OS and it older version...

i can isolate VIR_DOMAIN_UNDEFINE_KEEP_NVRAM VIR_DOMAIN_UNDEFINE_NVRAM parameters but if some use OVMF(UEFI bios), it cannot delete instance or migrate...

**Comment by ssbaksa** [comment]
My problem lays in fact that I can't find definition in libvirt.py. Correct me if I am wrong. At the end you can find my test which is working.

In file
/srv/webvirtcloud/instances/views.py
Line 25
from libvirt import libvirtError, VIR_DOMAIN_XML_SECURE, VIR_DOMAIN_UNDEFINE_KEEP_NVRAM, VIR_DOMAIN_UNDEFINE_NVRAM

You are calling "something" defined in /srv/webvirtcloud/venv/lib/python2.7/site-packages/libvirt.py

Searching for VIR_DOMAIN_XML_SECURE
VIR_DOMAIN_XML_SECURE defined at line 6781
# virDomainXMLFlags
VIR_DOMAIN_XML_SECURE = 1

Searching for VIR_DOMAIN_UNDEFINE_NVRAM
VIR_DOMAIN_UNDEFINE_NVRAM = 4 defined at line 6771
# virDomainUndefineFlagsValues
VIR_DOMAIN_UNDEFINE_MANAGED_SAVE = 1
VIR_DOMAIN_UNDEFINE_SNAPSHOTS_METADATA = 2
VIR_DOMAIN_UNDEFINE_NVRAM = 4

Searching for VIR_DOMAIN_UNDEFINE_KEEP_NVRAM
E486: Pattern not found: VIR_DOMAIN_UNDEFINE_KEEP_NVRAM  

Yust for fun of it i have aded missing variable at the end of file
/srv/webvirtcloud/venv/lib/python2.7/site-packages/libvirt.py

#test
VIR_DOMAIN_UNDEFINE_KEEP_NVRAM = 1

And now all is working as expected so it looks to me that someone in libvirt community forget to add that definition.

(venv) root@backup:/srv/webvirtcloud# python manage.py migrate
Operations to perform:
  Apply all migrations: accounts, admin, auth, computes, contenttypes, create, instances, logs, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying computes.0001_initial... OK
  Applying instances.0001_initial... OK
  Applying accounts.0001_initial... OK
  Applying accounts.0002_auto_20150325_0846... OK
  Applying accounts.0003_usersshkey... OK
  Applying accounts.0004_userattributes... OK
  Applying accounts.0005_userattributes_can_clone_instances... OK
  Applying accounts.0006_userattributes_max_disk_size... OK
  Applying accounts.0007_auto_20160426_0635... OK
  Applying accounts.0004_userinstance_is_vnc... OK
  Applying accounts.0008_merge... OK
  Applying accounts.0009_auto_20171026_0805... OK
  Applying accounts.0010_auto_20180625_1236... OK
  Applying accounts.0011_auto_20180625_1313... OK
  Applying accounts.0012_auto_20180625_1331... OK
  Applying accounts.0013_auto_20180625_1358... OK
  Applying accounts.0014_auto_20180808_1436... OK
  Applying accounts.0015_auto_20180808_1449... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying computes.0002_compute_details... OK
  Applying create.0001_initial... OK
  Applying create.0002_auto_20150325_0921... OK
  Applying instances.0002_instance_is_template... OK
  Applying instances.0003_instance_created... OK
  Applying instances.0004_auto_20180724_1136... OK
  Applying logs.0001_initial... OK
  Applying logs.0002_auto_20150316_1420... OK
  Applying logs.0003_auto_20150518_1855... OK
  Applying sessions.0001_initial... OK

**Comment by catborise** [comment]
as i said before you are using very old version of libvirt. as you see on this link https://libvirt.org/news-2016.html VIR_DOMAIN_UNDEFINE_KEEP_NVRAM added with version 2.30. but your libvirt version 1.3.1.

may be it is not work as expected while removing nvram but it is harmless to use it like your test.

**Comment by ssbaksa** [comment]
May I ask on which system do you build/test? Ubuntu, Debian, CentOS?

I will test docker to.

**Comment by catborise** [comment]
i have 10 host: the hosts operating system is Oracle Linux 8.1, i can also use centos8 or 7 with qemu-kvm-ev repo.
i have a guest on a host, it is also centos7 which is webvirtcloud.

I am not using docker but, docker is simple... you do not hassle with configurations...
docker uses an ubuntu image but it is a custom ubuntu image.

**Comment by ssbaksa** [comment]
Docker is working but only on 18.04. On 16.04 it trows exeptions while building.

I can see now the difference. While libvirt.py under Docker has defined VIR_DOMAIN_UNDEFINE_KEEP_NVRAM under virDomainUndefineFlagsValues the one under "normal 16.04" system doesn't. It looks like libvirt.py is automatically rebuild while installing depending on kvm/qemu/libvirt-bin capabilities are avaliable.

**Comment by catborise** [comment]
docker images is not related with host operating system or whereever it works. it uses its own repo/package version. you can use it on hosts and it does not interfere any package on host

**Comment by ssbaksa** [comment]
True. I know that. But, newer the less, the one under Ubuntu 16.04 failed to build and I don't want to loose any more time time on that. The one under 18.04 works as it should and it will take over as main Core cloud controller. Something started as minor upgrade ended up as a problem.

There is to many other things to do. Our main OpenStack cloud waits for re-installation solution and there is 70-something servers to reinstall from scratch :-)

**Comment by catborise** [comment]
omg openstack and it is bloody upgrades. :)) We have also use Openstack in different project and we need to update, but everyone else in that project play dead about upgrades.
migrating instances to new openstack hosts.... may god help you :)

**Comment by ssbaksa** [comment]
Then you know that great feeling. There is around 400 virtual machines there for our developers and this is heterogeneous environment with SuperMicro, HP Blade, Intel and HP rack servers. Bloody nightmare.
