### ISSUE TITLE
noVNC local scaling

### ISSUE THREAD

**Issue by haralambop** [retspen/webvirtcloud#297]
How can I apply the noVNC local scaling capability?

scaleViewport

Is a boolean indicating if the remote session should be scaled locally so it fits its container. When disabled it will be centered if the remote session is smaller than its container, or handled according to clipViewport if it is larger. Disabled by default.

**Comment by catborise** [comment]
It is a good option i think. For now it is static. But i can add this options to settings.py as constant.
i do not know if it should be dynamic or static... What do you think?

**Comment by catborise** [comment]
It is fixed with options.
