### ISSUE TITLE
How to attach (expose/passtrough) phisical disk device from host to guest instance?

### ISSUE THREAD

**Issue by lord-kyron** [retspen/webvirtcloud#298]
Hi @catborise 
how can I attach physical disks from the host to the instance guest from the UI?
I know I can edit the XML, but is there legitimate way to do it from the UI?
Am I right that first I need to expose the disk from the compute host as LVM storage and then attach it to the VM or?
Please, explain!
Thanks!

**Comment by catborise** [comment]
@lord-kyron hi. i want to ask why do you wan to do this? 
what is the situation. may be there are other choices...

you can add block or lvm disk to the guest. it is your choice, but redhat suggests lvm disk.

and also there are two choices while adding host devices to [guest.](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/virtualization_deployment_and_administration_guide/sect-manipulating_the_domain_xml-devices)
* normal disk 
* hostdev disk

hostdev not implemented with webvirtcloud but it is planned.
for now two methods require xml editing.

**Comment by lord-kyron** [comment]
@catborise I want to use ZFS RaidZ inside a VM, so my idea is to attach two disks as block devices directly passtrough from the host and setup zfs on top of them but from the VM they are attached to.

**Comment by lord-kyron** [comment]
@catborise ?

**Comment by catborise** [comment]
it is a complex action, brcause of that we did not implement it. you can use virt-manager for more complex additions. virt-manager supports hostdev and blockdevice additions.
