### ISSUE TITLE
No "Create instance" button

### ISSUE THREAD

**Issue by amarc** [retspen/webvirtcloud#3]
Hello,

I installed webvirtcloud, configured storage and network and yet I have no idea how to  create Instance. On instance tab there is message that says "Warning: You don't have any Instace" but there is no option to create one. Am i missing something or is this bug ? 

A.

**Comment by retspen** [comment]
Do you have GREEN PLUS button?

**Comment by amarc** [comment]
No, I do not. Here is how it looks like http://i.imgur.com/Z3MkAhQ.png
