### ISSUE TITLE
CSRF token problem

### ISSUE THREAD

**Issue by lord-kyron** [retspen/webvirtcloud#303]
@catborise - I am using the latest python3 build from your repo and it was working fine, but suddenly it started giving me only:

Forbidden (403)

CSRF verification failed. Request aborted.

no matter what I do - it always returns this. I cannot login even anymore.
Please, tell me how to fix this!
Thanks!

**Comment by catborise** [comment]
@lord-kyron i think response time is high. click login and wait... do not click more than one time.
check webvirtcloud env to see disk ram filesystem .

**Comment by lord-kyron** [comment]
@catborise - no, I've tried even with retspen version based on python 2.7 - doing the same.
It is now loading slow - just giving the error immediately.

**Comment by lord-kyron** [comment]
I;ve tried several different browsers and even re-installed webvirctcloud several times - same effect - on login even the very first time it gets 403 forbidden. Can it be something from the OS causing it?

**Comment by catborise** [comment]
@lord-kyron where do you install webvlrtcloud. directly on host? on docker? on a vm?

**Comment by lord-kyron** [comment]
directly on host - ubuntu 18.04

**Comment by catborise** [comment]
@lord-kyron, l recommend you seperate . lt will be safe and sound. 
use docker on host to seperate. it is easy... you dont have to learn deeply docker. look at webvirtcloud wiki. can you please try it. installation takes 5minutes.
(ny installation on a vm/docker)

**Comment by lord-kyron** [comment]
Ok, I will try, but looking at the config I woder - how can I use nginx reverse proxy from host to the docker installation. I mean - I know how to forward the web interface. But how to configure docker image for vnc reverse proxy over port 443 on the original host. My setup will be nginx on the host on port 443 to reverse proxy to webvirtcloud + vnc console. Can you suggest? I assume something like:
`docker run -d -p MY_reverse_proxy_port:80 -p my_vnc_reverse_proxy_port:6080 retspen/webvirtcloud:1`
 am I right?

**Comment by catborise** [comment]
@lord-kyron for now install docker for testing environment.
i think you should change also some files for reverse proxy

**Comment by lord-kyron** [comment]
I've installed the docker but have another problem - by default there is user admin. No user at all.
And when I go in the docker container and try to crate superuser with manage.py python tells me there is no Django. How should I login for the first time? I used you repo to build the docker.

**Comment by lord-kyron** [comment]
@catborise - I am now running the docker image like this:
`docker run -d -p 81:80 -p 6080:6080 retspen/webvirtcloud:1`
The web interface is accessible and I can login and connect to host. However - vnc is not working.
Which files should I change for the docker image (settings.py ?) to make it work? This is my ngin config:
`    location /static/ {
        root /srv/webvirtcloud;
        expires max;
    } 

    location / {
	proxy_pass http://localhost:81;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-for $proxy_add_x_forwarded_for;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 1200;
        proxy_read_timeout 1200;
        proxy_send_timeout 1200;
        client_max_body_size 1024M;
    }

    location /websockify {
        proxy_http_version 1.1;
        proxy_pass http://wsnovncd/;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 61s;
        proxy_buffering off;
    }
}

upstream wsnovncd {
    server localhost:6080;
}
`

**Comment by lord-kyron** [comment]
@catborise  - thank you! In docker it is working flawlessly!
