### ISSUE TITLE
New staff user cannot view instances

### ISSUE THREAD

**Issue by lord-kyron** [retspen/webvirtcloud#304]
Hi @catborise ,
I am using your latest build on python3 on docker.
I've created new user and grated him staff rights. Then I created a VM for him and added him in the owners of the VM.
However, when I login after that with the new staff user I am getting this error:
```
libvirtError at /instances/
internal error: Unable to parse URI qemu+tcp://Compute object (1)/system

Request Method: | GET
-- | --
http://mydomain.com:80/instances/
2.2.10
libvirtError
internal error: Unable to parse URI qemu+tcp://Compute object (1)/system
/srv/webvirtcloud/vrtManager/connection.py in get_connection, line 300
/srv/webvirtcloud/venv/bin/python3
3.6.9
['/srv/webvirtcloud',  '/srv/webvirtcloud/venv/bin',  '/srv/webvirtcloud/venv/lib/python36.zip',  '/srv/webvirtcloud/venv/lib/python3.6',  '/srv/webvirtcloud/venv/lib/python3.6/lib-dynload',  '/usr/lib/python3.6',  '/srv/webvirtcloud/venv/lib/python3.6/site-packages']
Mon, 6 Apr 2020 09:17:01 +0000
```
This is not happening when there is no VM added to be owned by this user. I guess it is some kind of user rights problem. Can you help?

**Comment by catborise** [comment]
@lord-kyron it seems connection error i will check it. thanks

**Comment by catborise** [comment]
@lord-kyron problem is solved. you can checkout. thanks for feedback

**Comment by lord-kyron** [comment]
@catborise - now I can see the VM , but this is showing on top:
![image](https://user-images.githubusercontent.com/39150122/78548276-33f5b180-7809-11ea-96a6-7ad7f7109627.png)

**Comment by catborise** [comment]
@lord-kyron same problem... i missed it. it is resolved.

**Comment by lord-kyron** [comment]
resolved indeed! Thanks!
