### ISSUE TITLE
IP VM can't display

### ISSUE THREAD

**Issue by letran3691** [retspen/webvirtcloud#305]
My webvirt don't show IP vm 
![image](https://user-images.githubusercontent.com/19284401/78562917-5658f080-7844-11ea-903f-c10c885af540.png)

vm get ip form network virbr0 , but webvirt can't display. webvirt has installed at other hosts, connect to kvm through ssh
someone help me please.

**Comment by catborise** [comment]
@letran3691 you have to enable guest-agent settings->option.
then install/start qemu-guest-agent to see ip

**Comment by letran3691** [comment]
> @letran3691 you have to enable guest-agent settings->option.
> then install/start qemu-guest-agent to see ip
thank you. I forget add tab qemu-guest-agent
