### ISSUE TITLE
Webvirtcloud with Remote Hypervisor

### ISSUE THREAD

**Issue by toddleish** [retspen/webvirtcloud#310]
I have installed Webvirtcloud on Ubuntu 18.04.  I want to control a KVM hypervisor that is running on CentOS7.  
When I create a new "Compute" in Webvirtcloud and then try to access that compute node, I get an error in Webvirtcloud that says `Error: authentication failed: authentication failed` .

I tried to run this on the hypervisor node: 
wget --no-check-certificate -O - https://clck.ru/9V9fH | sudo sh
but it fails because I am not running supervisor on that node.  Do I have to install Webvirtcloud on all hypervisor nodes?
![image](https://user-images.githubusercontent.com/10604947/81592965-0063f500-937c-11ea-80bd-b7f00159d3d1.png)

![image](https://user-images.githubusercontent.com/10604947/81593061-1f628700-937c-11ea-80cc-93a3612ab856.png)

**Comment by catborise** [comment]
@toddleish  No you dont have to install webvirtcloud on any hypervisor. One webvirtcloud can manage other hosts. 
Hypervisor node  does not Require supervisor... 
how did you connect to host from webvirtcloud? TCP? SSH?

**Comment by toddleish** [comment]
I was confused because the Webvirt instructions say:
Setup libvirt and KVM on server
    wget -O - https://clck.ru/9V9fH | sudo sh

I ran that command on the remote libvirt server and it gave me an error because "supervisor" was not installed on that machine.

Anyway, I got it figured out with SSH, but not TCP.  I think we can close this.
