### ISSUE TITLE
Launch New Instance with Webvirtcloud - Error

### ISSUE THREAD

**Issue by toddleish** [retspen/webvirtcloud#311]
I am setting up Webvirtcloud for the first time.  I have Webvirtcloud running on Ubuntu 18.04 and the KVM/Libvirt server running on CentOS7.  I tried to launch my first instance on Webvirtcloud, but get this error:
`Error: unsupported configuration: virtio-mouse is not supported by this QEMU binary`

I did a google search, but I can't find anything related to this error.  Do you have any hints to fix this?

![image](https://user-images.githubusercontent.com/10604947/81627562-b6026880-93bb-11ea-9482-2385791b9b67.png)

**Comment by catborise** [comment]
I think you are using old qemu version. Because of that some new features does not work.

On the hypervisor host run that cmd:
`virsh version`

Add new repo to host and update qemu and libvirt. 
Latest rpm package for Centos qemu 2.12 and libvirt 4.5

**Comment by catborise** [comment]
Kvm common repo contains latest rpm packages for libvirt and qemu-kvm

http://mirror.centos.plus.hr/centos/7/virt/x86_64/

**Comment by znue** [comment]
I got the same problem, but thanks to @catborise I try these cmd to update libvirt and qemu-kvm, and it works for me:
```
yum install centos-release-qemu-ev
yum update qemu-kvm libvirt
```

**Comment by toddleish** [comment]
Yes, thank you.  I meant to reply also.  I upgraded my CentOS libvirt that
way and all is well.
