### ISSUE TITLE
Error on fresh install with Docker image

### ISSUE THREAD

**Issue by lord-kyron** [retspen/webvirtcloud#326]
hi @Real-Gecko and @catborise 
I've used the latest version of the master repo here at the main retspen project and installed it using the docker image.
however, on first login I hit this error immediately:
```

Request Method: | GET
-- | --
http://myserver.com:80/
2.2.13
NoReverseMatch
Reverse for 'allinstances' not found. 'allinstances' is not a valid view function or pattern name.
/srv/webvirtcloud/venv/lib/python3.6/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 673
/srv/webvirtcloud/venv/bin/python3
3.6.9
['/srv/webvirtcloud',  '/srv/webvirtcloud/venv/bin',  '/srv/webvirtcloud/venv/lib/python36.zip',  '/srv/webvirtcloud/venv/lib/python3.6',  '/srv/webvirtcloud/venv/lib/python3.6/lib-dynload',  '/usr/lib/python3.6',  '/srv/webvirtcloud/venv/lib/python3.6/site-packages']

```
Can you help?

**Comment by lord-kyron** [comment]
This is happening only for the home page "/"
When I write manually /instances in the address bar it is loading normally.

**Comment by lord-kyron** [comment]
I think I've found the problem - for some reason I am cloning the latest version of the repo, but when I build the docker image, It is not using all latest commits, especially those with the "allinstaces" to "index" change. How is that possible?

**Comment by peterdk** [comment]
I did a install on Ubuntu, and cloned the master branch. But I get this error everytime, also after creating a vm.

`

Request Method: | POST
-- | --
http://peter-server:8002/computes/1/create/archs/x86_64/machines/q35/
2.2.13
NoReverseMatch
Reverse for 'instance' not found. 'instance' is not a valid view function or pattern name.
/var/www/webvirtcloud/venv/lib/python3.8/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 673
/var/www/webvirtcloud/venv/bin/python
3.8.2
['/var/www/webvirtcloud',  '/var/www/webvirtcloud/venv/bin',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/var/www/webvirtcloud/venv/lib/python3.8/site-packages']
wo, 17 Jun 2020 14:51:31 +0000

`

**Comment by Real-Gecko** [comment]
Try out [this version](https://github.com/retspen/webvirtcloud/tree/636b5bb1bc0065cc0e265cdf5118dca11c10f3f7)
Looks like I forgot to namespace some instances urls.
Generally I would not recommend using latest version as it is not yet well tested and a lot of things will be changed in near future.

**Comment by Real-Gecko** [comment]
Also [this version](https://github.com/retspen/webvirtcloud/tree/6d82c2820b96757b933321d86b70e7ce23da447e) is more stable as I was not adding anything at that point in time yet :D

**Comment by lord-kyron** [comment]
@Real-Gecko do you plan to update and fix the master branch soon (at least the namespaces in those instance URLs)?
Honestly, I prefer using the master branch, that is why I am asking.

**Comment by Real-Gecko** [comment]
I can do this, but @retspen is the boss who merges PRs :)

**Comment by lord-kyron** [comment]
I am sure he will merge the PR if it is for fixing something that is not working right at the moment.

**Comment by Real-Gecko** [comment]
LOL, PR no 327 fixed issue no 326 :D
