### ISSUE TITLE
Console password not working for "lite" console type

### ISSUE THREAD

**Issue by lord-kyron** [retspen/webvirtcloud#329]
Hi @Real-Gecko @catborise 
I tried to set console password from instance settings and found, that after being set, the password is only requested when trying to open FULL console connection type.
When I choose "LITE" - I am directly connected to the console without being asked for password, which makes setting the password useless in first place.

Can you, please, look and fix that?
Thanks!

**Comment by catborise** [comment]
hi @lord-kyron real-frog works on backend heavily. changes very wide. because of that i pause. 
we can look at it after settle. 
it should not open console if it is password protected. i will look at it.

**Comment by catborise** [comment]
@lord-kyron is problem solved?

**Comment by lord-kyron** [comment]
Yes, solved. Thanks!
