### ISSUE TITLE
Super linter build time is ridiculous

### ISSUE THREAD

**Issue by Real-Gecko** [retspen/webvirtcloud#331]
@catborise I merged master branch to my instances branch and tried out super linter and it's [sloooooooow](https://github.com/Real-Gecko/webvirtcloud/runs/809906239). Do we really need it?

**Comment by catborise** [comment]
no we do not needed but it could be fine. it can be refined or remove.

**Comment by Real-Gecko** [comment]
The funniest part is that linter itself works only for 4 seconds, while everything else takes 6:28. Maybe there're ways to optimize it.

**Comment by catborise** [comment]
it is riddiculus to build their image for every time for installing updating etc. they should use a prebuild image.
6.28 is too much. when i tried it took less time...

**Comment by catborise** [comment]
it is fixed now total time is 1 minute. build time 44 second.

**Comment by Real-Gecko** [comment]
https://github.com/Real-Gecko/webvirtcloud/runs/817207436
2 minutes 36 seconds

**Comment by Real-Gecko** [comment]
Now time varies from 1:30 to 2:30 which is better than 6 minutes.
