### ISSUE TITLE
after offline migration error appears although it is successfull

### ISSUE THREAD

**Issue by catborise** [retspen/webvirtcloud#335]
@Real-Gecko real-gecko/instances branch
![resim](https://user-images.githubusercontent.com/1725643/85923869-3a8b4680-b897-11ea-8904-d7dcc067a58c.png)

**Comment by Real-Gecko** [comment]
Which page is it at?

**Comment by catborise** [comment]
instance migration.
instance->settings->migrate

**Comment by Real-Gecko** [comment]
Desync?
https://github.com/retspen/webvirtcloud/issues/336#issuecomment-650910903

**Comment by Real-Gecko** [comment]
I think it was fixed in instances branch, can you please recheck?

**Comment by Real-Gecko** [comment]
Cool
