### ISSUE TITLE
@real-gecko instances branch issues

### ISSUE THREAD

**Issue by catborise** [retspen/webvirtcloud#336]
branch real-gecko/instances 
@Real-Gecko inbound or outbound qos adding to instance network card does not work.

**Comment by catborise** [comment]
@Real-Gecko cloning an instance does not work

**Comment by catborise** [comment]
@Real-Gecko console does not work. token value is wrong
![resim](https://user-images.githubusercontent.com/1725643/85924238-8b9c3a00-b899-11ea-9084-5e607c3e2b47.png)

**Comment by catborise** [comment]
@Real-Gecko brief info about ram and cpu does not show
![resim](https://user-images.githubusercontent.com/1725643/85924378-973c3080-b89a-11ea-8034-e2225b21ae60.png)

**Comment by catborise** [comment]
changing instance title&description second time is not working

**Comment by catborise** [comment]
@Real-Gecko regular user(not superuser/staff) cannot pause his instance.
reguler user clone instance does not work also.

**Comment by Real-Gecko** [comment]
> @Real-Gecko inbound or outbound qos adding to instance network card does not work.

Fixed that. 05f1ec179e336a44d4329552d5235da84b404d8f

**Comment by Real-Gecko** [comment]
> @Real-Gecko cloning an instance does not work

Fixed a060be8ceb8c0d82459eb2a2ff5c00366666bbae

**Comment by catborise** [comment]
if an instance removed from libvirt but not webvirtcloud database it causes error and does not load allinstances page.
![image](https://user-images.githubusercontent.com/1725643/85975364-85fd3c00-b9e0-11ea-8b5a-65b0f6034d38.png)

**Comment by Real-Gecko** [comment]
> if an instance removed from libvirt but not webvirtcloud database it causes error and does not load allinstances page.

Yep, that's because we do not call refresh_instance_database on every compute in allinstances, I'll add it, but it'll slow down the page.
I think all refreshes must be performed on application start and then removed completely from views. If host is controlled only by WVC then no desync will happen. If not then we will have to call refresh every time we go to allinstances/compute instances views.

**Comment by Real-Gecko** [comment]
> console does not work

93c15c806a5ef73620dcaccc6b95189460cc2a42

**Comment by Real-Gecko** [comment]
> info about ram and cpu does not show

bbd770ce9f48e7f9744442f0134b05d949b6b42f

**Comment by catborise** [comment]
selected options does not show
![image](https://user-images.githubusercontent.com/1725643/85976893-302a9300-b9e4-11ea-9b7d-dafdc5081b8b.png)

![image](https://user-images.githubusercontent.com/1725643/85976937-46d0ea00-b9e4-11ea-9143-dffbcd1aefd6.png)

**Comment by catborise** [comment]
> > if an instance removed from libvirt but not webvirtcloud database it causes error and does not load allinstances page.
> 
> Yep, that's because we do not call refresh_instance_database on every compute in allinstances, I'll add it, but it'll slow down the page.
> I think all refreshes must be performed on application start and then removed completely from views. If host is controlled only by WVC then no desync will happen. If not then we will have to call refresh every time we go to allinstances/compute instances views.

this situation appears not only remove instance manually from libvirt. sometimes some actions raising an exception and prevents removing db records...
we can provide an option to users, wvc control instances strictly  or not. if user select instance control strictly from appsettings, wvc checks duplicate instances, refreshing db records everytime, name and uuid control as before.
or
may be we could async batch jobs which updates db records time to time.
beside that we need also some batch implementations: like move all instances to another hosts. shutdown/suspend/restart all instances on a host. live backup. live clone etc.
adding celery to project can help us, isnt it? what do you think?

**Comment by catborise** [comment]
clone instance does not work yet.
![image](https://user-images.githubusercontent.com/1725643/85979356-ff009180-b9e8-11ea-8cee-862961a966ae.png)

**Comment by Real-Gecko** [comment]
> adding celery to project can help us, isnt it? what do you think?

I did not work with Celery, so I cannot say anything about it.

> changing instance title&description second time is not working

This is due to `virDomain.XMLDesc(0)`, if instance is running then it returns XML that was active on domain start, title and description won't change until domain is restarted. To get XML that will be active on next domain start we need to call `virDomain.XMLDesc(2):
https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainGetXMLDesc
https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainXMLFlags

**Comment by Real-Gecko** [comment]
> selected options does not show

Does not work in master too
This part causes trouble:
https://github.com/retspen/webvirtcloud/blob/f23e6b000fc8f5167956dad8ac3422e15f90bda2/instances/templates/instance.html#L1238-L1240

**Comment by Real-Gecko** [comment]
> clone instance does not work yet.

Something is wrong with DB, did you apply migrations?

**Comment by catborise** [comment]
> > clone instance does not work yet.
> 
> Something is wrong with DB, did you apply migrations?

they are allied applied.
problem is related with instance id. which should different from source instance.
"The above exception (NOT NULL constraint failed: accounts_userinstance.instance_id) was the direct cause of the following exception:"

i remove db and migrate it again.. problem continues...

**Comment by catborise** [comment]
another problem with instance db records.
i remove db.sqlite3 and create with migrate command.
login to the wvc
add an host.
click to instances(all instances)
the list is empty. not showing anything.
---
go to host.
click to instances
then go to all instances. instances are listed.

we have to find a solution to this hiccup.

**Comment by Real-Gecko** [comment]
> another problem with instance db records.
> 
>     * i remove db.sqlite3 and create with migrate command.
> 
>     * login to the wvc
> 
>     * add an host.
> 
>     * click to instances(all instances)
> 
>     * the list is empty. not showing anything.
> 
> 
>     * go to host.
> 
>     * click to instances
> 
>     * then go to all instances. instances are listed.
> 
> 
> we have to find a solution to this hiccup.

Yep, because of things described here
https://github.com/retspen/webvirtcloud/issues/336#issuecomment-650910903
Will fix that

**Comment by Real-Gecko** [comment]
> they are all applied.
> problem is related with instance id. which should different from source instance.
> "The above exception (NOT NULL constraint failed: accounts_userinstance.instance_id) was the direct cause of the following exception:"
> 
> i remove db and migrate it again.. problem continues...

Can you provide reproduction steps? Does cloned instance belong to any user?

**Comment by catborise** [comment]
> > they are all applied.
> > problem is related with instance id. which should different from source instance.
> > "The above exception (NOT NULL constraint failed: accounts_userinstance.instance_id) was the direct cause of the following exception:"
> > i remove db and migrate it again.. problem continues...
> 
> Can you provide reproduction steps? Does cloned instance belong to any user?

i control it. it does not belong any user.
i track it the problem exception misleading. 
the problem is related with not cloned disk instances: stg.createXMLFrom(vol_clone_xml, vol, meta_prealloc) fires an exception.
 except Exception as e:  messages.error(request, e) catches it print messages then try to save instances to user instance, but there is no new_instance uuid and new_instance.id
( user_instance = UserInstance(instance_id=new_instance.id, user_id=request.user.id, is_delete=True) )
![image](https://user-images.githubusercontent.com/1725643/85987226-08dcc180-b9f6-11ea-8706-052ff523f98d.png)
there should be return in except. or move user_instance create/save to in try/except will solve that

**Comment by catborise** [comment]
create a group. then click to see details... does not work

**Comment by Real-Gecko** [comment]
> if an instance removed from libvirt but not webvirtcloud database it causes error and does not load allinstances page.

https://github.com/Real-Gecko/webvirtcloud/commit/63c8151f28b0b50446f1875c870def7f1afb4c94

**Comment by catborise** [comment]
appsettings page also show two notification
![image](https://user-images.githubusercontent.com/1725643/86000036-a98ea980-ba15-11ea-80ca-53efccfdac5c.png)

**Comment by Real-Gecko** [comment]
> appsettings page also show two notification

`include messages_block.html` must be removed from all templates.

**Comment by catborise** [comment]
instance views nongrouped does not work as expected.

**Comment by Real-Gecko** [comment]
> instance views nongrouped does not work as expected.

What exactly is wrong?

**Comment by Real-Gecko** [comment]
> create a group. then click to see details... does not work

Not related to instances

**Comment by catborise** [comment]
non grouped view
![image](https://user-images.githubusercontent.com/1725643/86003592-b5c93580-ba1a-11ea-90db-be15ad4bce8d.png)

it should be like that
![image](https://user-images.githubusercontent.com/1725643/86003638-c4afe800-ba1a-11ea-8370-c49a28586900.png)

this pieces of code seems to ? grouped and nongrouped view does need same info but why is this code:
![image](https://user-images.githubusercontent.com/1725643/86003838-0f316480-ba1b-11ea-9a39-386038c80464.png)

**Comment by Real-Gecko** [comment]
> selected options does not show

88ea491a0bb96644de9d42330df80f4189659707 for settings too

**Comment by Real-Gecko** [comment]
> non grouped view

676d66076762c9de5e24eda312be83aa2a4969ce

**Comment by Real-Gecko** [comment]
> except Exception as e: messages.error(request, e) catches it print messages then try to save instances to user instance, but there is no new_instance uuid and new_instance.id

f3bde2408ce1303e06a5e2a25d516d8a394e08d8 I made it look like so

```python
        try:
            new_uuid = instance.proxy.clone_instance(clone_data)
            new_instance.uuid = new_uuid
            new_instance.save()
            user_instance = UserInstance(instance_id=new_instance.id, user_id=request.user.id, is_delete=True)
            user_instance.save()
        except Exception as e:
            messages.error(request, e)
```
Can you try again and see if it works?

**Comment by catborise** [comment]
clone is working now. no problem.
instance fixed.

**Comment by catborise** [comment]
user info missing. host title missing
![image](https://user-images.githubusercontent.com/1725643/86009587-12305300-ba23-11ea-971f-dfb2b07740bb.png)

**Comment by Real-Gecko** [comment]
> regular user(not superuser/staff) cannot pause his instance.

For some reason suspending instances is allowed only for superusers I left this functionality intact.

https://github.com/retspen/webvirtcloud/blob/f23e6b000fc8f5167956dad8ac3422e15f90bda2/instances/views.py#L682-L687

**Comment by Real-Gecko** [comment]
> user info missing. host title missing

2f82055c27eef8a4d89a7d7c5659c8720bb26d1a

**Comment by Real-Gecko** [comment]
So, looks like everything is fixed, can you please confirm?

**Comment by catborise** [comment]
instance settings tab actions returns to main instance page.
they should return to options or disk tab
return redirect(request.META.get('HTTP_REFERER') + #options/#disk/etc)

.
def delete_vol(request, pk):
def detach_vol(request, pk):
def add_cdrom(request, pk):
def detach_cdrom(request, pk, dev):
def mount_iso(request, pk):
def add_existing_vol(request, pk):

**Comment by catborise** [comment]
migration completed successfully. but error happens like before
![image](https://user-images.githubusercontent.com/1725643/86086455-7d713800-baaa-11ea-8547-28443be8bda7.png)

**Comment by catborise** [comment]
steps:
1. convert one instance to template
2. add an owner which can clone/delete/vnc
3. login with this user(owner)
4. create a clone from template
5. delete cloned instance.
-> http404 error than instance not found error

**Comment by catborise** [comment]
console access from instance list does not work yet:
![image](https://user-images.githubusercontent.com/1725643/86087216-50258980-baac-11ea-95a5-cc27416d0d0d.png)

**Comment by Real-Gecko** [comment]
> console access from instance list does not work yet

not superuser?

**Comment by catborise** [comment]
> > console access from instance list does not work yet
> 
> not superuser?

super user. i did not try not superuser

**Comment by catborise** [comment]
click an instance suspend button. unexpected error appears
![image](https://user-images.githubusercontent.com/1725643/86087575-3a649400-baad-11ea-8eb9-71721416a198.png)

**Comment by catborise** [comment]
delete instance does not ask any confirmation. it deletes immediately. isnt it dangerous?

**Comment by Real-Gecko** [comment]
> delete instance does not ask any confirmation. it deletes immediately. isnt it dangerous?

Yep it is, but this ugly js alert is an atrocity. I'll replace it with simple confirmation page.

**Comment by Real-Gecko** [comment]
> migration completed successfully. but error happens like before

Can you show full stack trace? Don't forget to remove any sensitive data from it.

**Comment by Real-Gecko** [comment]
> migration completed successfully. but error happens like before

Does it happen in master branch?

**Comment by catborise** [comment]
it is not a problem i think it is only a notification message. master branch does not show it on the page, but only console. 
instance branch shows that libvirt error which is "libvirt: QEMU Driver error : Domain not found: no domain with matching name 'rpmbuild'" with a notification.

**Comment by Real-Gecko** [comment]
> master branch does not show it on the page, but only console

I want to track down the error to the line it's happening at. Even if it goes to console I think we have to fix it.

**Comment by catborise** [comment]
i do not now how to trace it. only one libvirterror message appears and continue. i will debug it, may be i can see.

**Comment by catborise** [comment]
i figure it out. it because of autostart query.
![image](https://user-images.githubusercontent.com/1725643/86212829-6e10ee00-bb81-11ea-9169-36ab59d60ba8.png)

i did try it disabling it:
#autostart = instance.proxy.get_autostart()
# if autostart:
    #    conn_new.set_autostart(1)
    #    conn_new.close()
error is gone.
because there is not instance any more it is moved. we should call "autostart = instance.proxy.get_autostart()" before migrate not after migrate.
may it can be:
![image](https://user-images.githubusercontent.com/1725643/86213807-ecba5b00-bb82-11ea-9103-d049f0df8e99.png)

**Comment by catborise** [comment]
remove instance whom disk is removed/missing etc. causes eror. it should specify a notification and should return to instance.
![image](https://user-images.githubusercontent.com/1725643/86225115-7887b380-bb92-11ea-9f12-4cb318a99f8c.png)

**Comment by catborise** [comment]
moving this from instances/utils.py/migrate_instance:
![1](https://user-images.githubusercontent.com/1725643/86247061-9ebe4b00-bbb4-11ea-9d76-11d32cd86d32.PNG)
to
![1](https://user-images.githubusercontent.com/1725643/86246905-6dde1600-bbb4-11ea-9869-254ac11a366e.PNG)
will solve notifications problem.

**Comment by Real-Gecko** [comment]
0771f72a25c5a52f1aa41ac9e7ee8b163062bf8e
Here's the latest commit that fixes all issues discussed above, please confirm that things are working.

**Comment by catborise** [comment]
> i figure it out. it because of autostart query.
> ![image](https://user-images.githubusercontent.com/1725643/86212829-6e10ee00-bb81-11ea-9169-36ab59d60ba8.png)
> 
> i did try with disabling it:
> 
> ```
> #autostart = instance.proxy.get_autostart()
> # if autostart:
>     #    conn_new.set_autostart(1)
>     #    conn_new.close()
> ```
> 
> error is gone.
> because there is not instance any more it is moved. we should call "autostart = instance.proxy.get_autostart()" before migrate not after migrate.
> may it can be:
> ![image](https://user-images.githubusercontent.com/1725643/86213807-ecba5b00-bb82-11ea-9103-d049f0df8e99.png)

what about that? 
did you forget

**Comment by Real-Gecko** [comment]
> what about that?
> did you forget

6eca1d886ae2d08a114e35e3572238edfd07d196
Fixed

**Comment by catborise** [comment]
all libvirt actions need to be encapsulate with try/except block.
libvirt always could be produce an error. this should not be crash application.
![image](https://user-images.githubusercontent.com/1725643/86324045-9878af00-bc46-11ea-95d6-905622555e12.png)

could you implement that with a decorator?

```
def poweron(request, pk):
    instance = get_instance(request.user, pk)
    if instance.is_template:
        messages.warning(request, _("Templates cannot be started."))
    else:
    /// try
        instance.proxy.start()
   /// except
        addlogmsg(request.user.username, instance.name, _("Power On"))

    return redirect(request.META.get('HTTP_REFERER'))


def powercycle(request, pk):
    instance = get_instance(request.user, pk)
    instance.proxy.force_shutdown()
    instance.proxy.start()
    addlogmsg(request.user.username, instance.name, _("Power Cycle"))
    return redirect(request.META.get('HTTP_REFERER'))


def poweroff(request, pk):
    instance = get_instance(request.user, pk)
    instance.proxy.shutdown()
    addlogmsg(request.user.username, instance.name, _("Power Off"))

    return redirect(request.META.get('HTTP_REFERER'))


@superuser_only
def suspend(request, pk):
    instance = get_instance(request.user, pk)
    instance.proxy.suspend()
    addlogmsg(request.user.username, instance.name, _("Suspend"))
    return redirect(request.META.get('HTTP_REFERER'))


@superuser_only
def resume(request, pk):
    instance = get_instance(request.user, pk)
    instance.proxy.resume()
    addlogmsg(request.user.username, instance.name, _("Resume"))
    return redirect(request.META.get('HTTP_REFERER'))


def force_off(request, pk):
    instance = get_instance(request.user, pk)
    instance.proxy.force_shutdown()
    addlogmsg(request.user.username, instance.name, _("Force Off"))
    return redirect(request.META.get('HTTP_REFERER'))
```

**Comment by catborise** [comment]
same error problem which cause crash is also valid for destroy
may be you should change method like below
```
def destroy(request, pk):
    instance = get_instance(request.user, pk)
    try:
        userinstance = instance.userinstance_set.get(user=request.user)
    except:
        userinstance = UserInstance(is_delete=request.user.is_superuser)

    if request.method == 'POST' and userinstance.is_delete:
        if instance.proxy.get_status() == 1:
            instance.proxy.force_shutdown()

        try:
            if request.POST.get('delete_disk', ''):
                snapshots = sorted(instance.proxy.get_snapshot(
                ), reverse=True, key=lambda k: k['date'])
                for snapshot in snapshots:
                    instance.proxy.snapshot_delete(snapshot['name'])
                instance.proxy.delete_all_disks()

            if request.POST.get('delete_nvram', ''):
                instance.proxy.delete(VIR_DOMAIN_UNDEFINE_NVRAM)
            else:
                instance.proxy.delete(VIR_DOMAIN_UNDEFINE_KEEP_NVRAM)

            instance.delete()
            msg = _("Destroy Instance")

        except libvirtError as err:
            msg = err
            messages.error(request, msg)
            return redirect(request.META.get('HTTP_REFERER'))

        addlogmsg(request.user, instance.name, msg)

        return redirect(reverse('instances:index'))

    return render(
        request,
        'instances/destroy_instance_form.html',
        {
            'instance': instance,
            'userinstance': userinstance,
        },
    )
```

also
i think you move the choices to confirm dialog. it should be changed with a proper message
![image](https://user-images.githubusercontent.com/1725643/86325022-16898580-bc48-11ea-954a-ac6f00dd8b2e.png)

**Comment by Real-Gecko** [comment]
> libvirt always could be produce an error. this should not crash application.

Do you have ExceptionMiddleware enabled?
```python
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'login_required.middleware.LoginRequiredMiddleware',
    'django.contrib.auth.middleware.RemoteUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'appsettings.middleware.AppSettingsMiddleware',
    'webvirtcloud.middleware.ExceptionMiddleware',
]
```

**Comment by Real-Gecko** [comment]
![Screenshot_20200702_124703](https://user-images.githubusercontent.com/2231969/86325661-3a59c500-bc62-11ea-8541-2ce1d88616af.png)

**Comment by lord-kyron** [comment]
Hey guys, shouldn't it be better to create a Discord chat channel and move those conversations there? It will be faster and not so spamming. I can create the channel if you are ok with it?

**Comment by catborise** [comment]
hmm. no it was not enabled. i enable it. nice it works as expected :)

**Comment by catborise** [comment]
in past, i want to create a channel for project in https://gitter.im/ but retspen does not respond. 
discord will be fine. 
this place is not a suitable for that style communication.

you can add communication info to readme

**Comment by Real-Gecko** [comment]
> I can create the channel if you are ok with it?

Make it happen.

**Comment by lord-kyron** [comment]
It was done:
https://discord.gg/McyJ9m

Come in!
And someone of you - please, add the link to the channel to the README!
Thanks!

**Comment by Real-Gecko** [comment]
Closing as #342 was merged.
