### ISSUE TITLE
Problem updating docker image installation

### ISSUE THREAD

**Issue by lord-kyron** [retspen/webvirtcloud#337]
@catborise @Real-Gecko  - since several last releases, I found out that the `.git` folder is missing when I make a docker installation.
I am unable to update existing docker installation, so to implement every new feature I must re-compile and re-create the whole docker image again. 
Can you please check when is wrong and missing and fix that?
Thanks!

**Comment by catborise** [comment]
.git folder is not needed to update container... 
check with "git status" if there is a file which was edited. if it is, it gives error to update.

you can build a new one. copy old db.sqlite3 file, it will work.

**Comment by lord-kyron** [comment]
I am using fresh install without modifications and I am getting this when I activate the venv and try to execute git command (no matter if git pull or git status):
```
# source venv/bin/activate
(venv) root@bcfc8101bb6b:/srv/webvirtcloud# git status
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by catborise** [comment]
@lord-kyron if you want to add existing .git directories
before build you can remove ".dockerignore"
docker ignore file prevents to copy some files to container.

**Comment by lord-kyron** [comment]
Yes, I was thinking of this. Ok will try and give you feedback.
