### ISSUE TITLE
@retspen - webvirtcloud discord channel and itegration

### ISSUE THREAD

**Issue by lord-kyron** [retspen/webvirtcloud#338]
@retspen - me, @catborise and @Real-Gecko made a Discord chat channel, in which we (and everyone else) can discuss thigns about WebVirtCloud.
However, there is an integration with your master repo that we want to do. We want just simply when you push (or merge) new commit to the master repo, the Discord channel to receive push notification about this commit.
Can you please, follow steps from number 2 to number 6 from this tutorial:
https://superuser.com/questions/1189901/can-i-integrate-a-discord-channel-with-github-pull-requests
And the webhook link that you should put under the Payload box is this one:
https://discordapp.com/api/webhooks/728158722060189766/2dqZeS1GVgnpxRhrQ36Z4IbkCR2IbBGE_IKsiKlj2fXyTF79Kh6gPYy3DxoyPcrOegIT

Please, do this integrate with the new channel of users and supports of webvirtcloud :)
Thank you!

**Comment by lord-kyron** [comment]
@retspen - will you do the integration, please?

**Comment by retspen** [comment]
Hello, 

Sorry for delay. Can you add link to the discord channel?

**Comment by lord-kyron** [comment]
@retspen 
This is the invitation link (with no limits and no expiration) to the channel: https://discord.gg/pWPF7Az
Did you make the integration with your master repo as I asked above? This will make possible any commit to send notification to the discord channel.

**Comment by retspen** [comment]
Done

**Comment by lord-kyron** [comment]
Thank you!
I can confirm it is working like a charm!
