### ISSUE TITLE
Is it possible to host panel on one machine and use it as instance too?

### ISSUE THREAD

**Issue by Games4k** [retspen/webvirtcloud#340]
Hello. I have a panel hosted on one machine, and I need to use it and be able to create VPSes on it too. Could you please tell me if it’s possible, and if it is, could you tell me more details on how to setup instance, as when I try to create it, I get
![B21257A0-C0D0-4454-99FA-9CA5682C98A5](https://user-images.githubusercontent.com/29690431/86418662-239e8700-bcd1-11ea-8cd8-a07586a10aa2.jpeg)
I do not understand where exactly should I add the key. Also, many of those commands for generating keys do not seem to work on Ubuntu 18.04...

**Comment by Games4k** [comment]
Also, there seems to be no guides on other 3 options:
- TCP
- TLS
- Local

**Comment by Games4k** [comment]
![68D39CF5-4EF5-4648-9002-5A5B5AD86947](https://user-images.githubusercontent.com/29690431/86419124-a247f400-bcd2-11ea-8b60-a6690dcffc3f.jpeg)
I’ve tried using local, but I get this error

**Comment by catborise** [comment]
this app purpose is managing kvm virtual machines. 
there are some guides : https://github.com/retspen/webvirtmgr/wiki
they are valid also for webvirtcloud

**Comment by Games4k** [comment]
Oh, thank you very much!

**Comment by Games4k** [comment]
Ok, even tho I've followed this guide
https://github.com/retspen/webvirtmgr/wiki/Setup-Local-connection

It seems like I'm unable to setup local connection. There is always this permission-denied error
![Screen Shot 2020-07-03 at 1 15 45 PM](https://user-images.githubusercontent.com/29690431/86464220-54ada480-bd2f-11ea-9208-99db94de2ce4.png)

**Comment by Games4k** [comment]
Most of the guides are also pretty outdated. May stuff I tried does not even work :(
when I do ssh-copy-id webvirtmgr@qemu-kvm-libvirt-host (from https://github.com/retspen/webvirtmgr/wiki/Setup-SSH-Authorization) it says:

```
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/var/www/.ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed

/usr/bin/ssh-copy-id: ERROR: ssh: Could not resolve hostname qemu-kvm-libvirt-host: Temporary failure in name resolution
```

**Comment by catborise** [comment]
this may be is not a thing what you want.
this app helps you create virtual machines on KVM hosts. if you do not have a KVM host you cannot use that.
may be you need "webmin" or like it is...

if you have a host(Qemu-kvm and libvirt installed) you can use that app whether you install this on host or container or a vm.

**Comment by Games4k** [comment]
From what I understand, this is something like Virtualizor or SolusVM, right? Also, I do have a dedicated server, so virtualization should not be a problem.

**Comment by catborise** [comment]
yes, it is like proxmox, solusvm but not sure virtualizor. if you want to manage your kvm virtual machines with web based tool webvirtcloud suits this purpose.

doc are not outdated but requires some linux skills. 

qemu-kvm-libvirt-host refers to your kvm host ip address or fqdn.

**Comment by Games4k** [comment]
Since docs are pretty outdated and I'm sure none of those still work, could I request you to update them? How hard could that be? I'm sure there are many confused users who'd love to use this, but sadly can not due to some issues due to outdated docs.

**Comment by Games4k** [comment]
Reading this issue helped me a lot:
https://github.com/retspen/webvirtcloud/issues/240 - you did not point out I need to add users to specific groups and that’s why I always had the permission denied issue

**Comment by Games4k** [comment]
Hey, now, since that problem is solved, I have a question for you. I’ve purchased an additional IP for a VPS that I’m going to create. The IP is routed to my server, however it’s new and I did not provision it. What do I need to do to allow connections from that IP and to use it for webvirtcloud? Do I just need to do simple IP address add command, or what. Please explain me as detailed as possible. Thank you very much!

**Comment by Games4k** [comment]
Also, where can I set SSH password?
