### ISSUE TITLE
2FA integration

### ISSUE THREAD

**Issue by lord-kyron** [retspen/webvirtcloud#341]
@catborise @Real-Gecko  - I am opening this issue in order to not forget to try to implement 2FA module for Django as we spoke!

**Comment by lord-kyron** [comment]
@catborise @Real-Gecko - since instances is merged, can you look at this now, please?

**Comment by lord-kyron** [comment]
@Real-Gecko @catborise  - can you make some last tries to implement this :( I know @Real-Gecko is not actively working on this project anymore, but some last commit about this, please?

**Comment by Real-Gecko** [comment]
Check out discord chat.

**Comment by lord-kyron** [comment]
Working as expected on first test. Please, create PR to the master repo so that it can be merged. Thanks!

**Comment by catborise** [comment]
before login, if you activate it you cannot login. may be it should be fixed. may be it could activate after login admin account.

**Comment by lord-kyron** [comment]
That is what I asked @Real-Gecko - can one of you guys make it possible to activate it the settings.py, but this to activate only the option to enable it in the admin settings. Like if you say enable=true - to have an option in the admin panel. If you say enable=false this option will not be present there. But if you will enable or disable it in admin this will actually turn it on or off.

**Comment by Real-Gecko** [comment]
Solution is obvious: disable in `settings.py`, login, grab qr code, enable in `settings.py`. If we put the option inside admin interface you can easily end in scenario like this: you enable, log out without qr and that's it, you cannot disable OTP now without connecting to your database, which requires a little bit more than writing `vi settings.py`.


> Like if you say enable=true - to have an option in the admin panel. If you say enable=false this option will not be present there.

But it's basically the same, if you're locked out you'll need to edit `settings.py` which is the same as it is now.

**Comment by lord-kyron** [comment]
> Solution is obvious: disable in `settings.py`, login, grab qr code, enable in `settings.py`. If we put the option inside admin interface you can easily end in scenario like this: you enable, log out without qr and that's it, you cannot disable OTP now without connecting to your database, which requires a little bit more than writing `vi settings.py`.
> 
> > Like if you say enable=true - to have an option in the admin panel. If you say enable=false this option will not be present there.
> 
> But it's basically the same, if you're locked out you'll need to edit `settings.py` which is the same as it is now.

This is true actually. @catborise  ?

**Comment by lord-kyron** [comment]
@catborise - are you going to offer some fix or this approach is sufficient?

**Comment by catborise** [comment]
i think it is enough for now. the other solution is nice but there is too overhead.

**Comment by Real-Gecko** [comment]
I actually have an idea how to improve current functionality, will implement it soon.

**Comment by lord-kyron** [comment]
I am re-opening the issue again then @Real-Gecko
