### ISSUE TITLE
found SyntaxError: invalid syntax in httpd error_log about venv/bin/activate on CentOS 7

### ISSUE THREAD

**Issue by xujianhua1974** [retspen/webvirtcloud#348]
I installed webvirtcloud under directory /home/pyprojects/webvirtcloud using apache httpd with wgsi module, without using nginx but found error in error_log about venv/bin/activate, and can't open the website http://serverip:6080.  I configured webvirtcloud as a virtual host with a configuration file '/etc/httpd/conf.d/virtualhost_webvirtcloud.conf' running on apache httpd. I have created virtualenv in venv directory and installed  pypi packages according to conf/requirements.txt with the same version specified by the conf/requirements.txt, and migrate the project sqlite3 database without errors. 
I have installed other Django projects using apache httpd with wgsi module and they run good.  I don't know why this webvirtcloud can't run good.  I appreciate anyone's help.

**Comment by catborise** [comment]
please use code formatting to make it more readable

**Comment by xujianhua1974** [comment]
I installed webvirtcloud under directory /home/pyprojects/webvirtcloud using apache httpd with wgsi module, without using nginx but found error in error_log about venv/bin/activate, and can't open the website http://serverip:6080. I configured webvirtcloud as a virtual host with a configuration file '/etc/httpd/conf.d/virtualhost_webvirtcloud.conf' running on apache httpd. I have created virtualenv in venv directory and installed pypi packages according to conf/requirements.txt with the same version specified by the conf/requirements.txt, and migrate the project sqlite3 database without errors.
I have installed other Django projects using apache httpd with wgsi module and they run good. I don't know why this webvirtcloud can't run good. I appreciate anyone's help.

1.Here is part of error_log about webvirtualcloud
`[Fri Jul 24 23:12:16.850728 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136] mod_wsgi (pid=30339): Exception occurred processing WSGI script '/home/pyprojects/webvirtcloud/webvirtcloud/wsgi_custom.py'.
[Fri Jul 24 23:12:16.850943 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136] Traceback (most recent call last):
[Fri Jul 24 23:12:16.851022 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136] File "/home/pyprojects/webvirtcloud/webvirtcloud/wsgi_custom.py", line 16, in
[Fri Jul 24 23:12:16.851038 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136] '/home/pyprojects/webvirtcloud/venv/bin/activate', 'exec'))
[Fri Jul 24 23:12:16.851079 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136] File "/home/pyprojects/webvirtcloud/venv/bin/activate", line 5
[Fri Jul 24 23:12:16.851110 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136] if [ "${BASH_SOURCE-}" = "$0" ]; then
[Fri Jul 24 23:12:16.851170 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136] ^
[Fri Jul 24 23:12:16.851202 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136] SyntaxError: invalid syntax`

2. Here is wsgi_custom.py modified with correct directory
`[root@djsvr webvirtcloud]# more webvirtcloud/wsgi_custom.py
"""
WSGI config for webvirtcloud project.

It exposes the WSGI callable as a module-level variable named application.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/howto/deployment/wsgi/
"""
import os
import sys

from django.core.wsgi import get_wsgi_application
execfile('/home/pyprojects/webvirtcloud/venv/bin/activate_this.py', dict(file='/home/pyprojects/webvirtcloud/venv/bin/activate_this.py'))

exec(compile(open('/home/pyprojects/webvirtcloud/venv/bin/activate', "rb").read(),
'/home/pyprojects/webvirtcloud/venv/bin/activate', 'exec'))

sys.path.append('/home/pyprojects/webvirtcloud')

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'webvirtcloud.settings')

application = get_wsgi_application()
[root@djsvr webvirtcloud]#`

3. Here is virtual host configuration /etc/httpd/conf.d/virtualhost_webvirtcloud.conf
`(venv) [root@djsvr webvirtcloud]# more /etc/httpd/conf.d/virtualhost_webvirtcloud.conf 
<VirtualHost *:6080>
	ServerName djsvr.comhead.com.cn
	ServerAlias comhead.com.cn
	ServerAdmin xujianhua@comhead.com.cn
	
	DocumentRoot /home/pyprojects/webvirtcloud

	Alias /static /home/pyprojects/webvirtcloud/static
	Alias /media /home/pyprojects/webvirtcloud/media

	<Directory "/home/pyprojects/webvirtcloud/static">
		# AllowOverride None
		Require all granted
	</Directory>

	<Directory "/home/pyprojects/webvirtcloud/media">
		# AllowOverride None
		Require all granted
	</Directory>

	WSGIDaemonProcess webvirtcloud python-path=/home/pyprojects/webvirtcloud threads=2 maximum-requests=1000 display-name=webvirtcloud
	WSGIProcessGroup webvirtcloud

	WSGIScriptAlias / /home/pyprojects/webvirtcloud/webvirtcloud/wsgi_custom.py

	<Directory "/home/pyprojects/webvirtcloud/webvirtcloud">
		<Files "wsgi_custom.py">
			# AllowOverride None
			Require all granted
		</Files>
	</Directory>

</VirtualHost>`

**Comment by xujianhua1974** [comment]
`[Fri Jul 24 23:12:16.850728 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136] mod_wsgi (pid=30339): Exception occurred processing WSGI script '/home/pyprojects/webvirtcloud/webvirtcloud/wsgi_custom.py'.
[Fri Jul 24 23:12:16.850943 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136] Traceback (most recent call last):
[Fri Jul 24 23:12:16.851022 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136]   File "/home/pyprojects/webvirtcloud/webvirtcloud/wsgi_custom.py", line 16, in <module>
[Fri Jul 24 23:12:16.851038 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136]     '/home/pyprojects/webvirtcloud/venv/bin/activate', 'exec'))
[Fri Jul 24 23:12:16.851079 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136]   File "/home/pyprojects/webvirtcloud/venv/bin/activate", line 5
[Fri Jul 24 23:12:16.851110 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136]     if [ "${BASH_SOURCE-}" = "$0" ]; then
[Fri Jul 24 23:12:16.851170 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136]                            ^
[Fri Jul 24 23:12:16.851202 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136] SyntaxError: invalid syntax`

**Comment by xujianhua1974** [comment]
1. Here is part of error_log about webvirtualcloud
`[Fri Jul 24 23:12:16.850728 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136] mod_wsgi (pid=30339): Exception occurred processing WSGI script '/home/pyprojects/webvirtcloud/webvirtcloud/wsgi_custom.py'.
[Fri Jul 24 23:12:16.850943 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136] Traceback (most recent call last):
[Fri Jul 24 23:12:16.851022 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136]   File "/home/pyprojects/webvirtcloud/webvirtcloud/wsgi_custom.py", line 16, in <module>
[Fri Jul 24 23:12:16.851038 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136]     '/home/pyprojects/webvirtcloud/venv/bin/activate', 'exec'))
[Fri Jul 24 23:12:16.851079 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136]   File "/home/pyprojects/webvirtcloud/venv/bin/activate", line 5
[Fri Jul 24 23:12:16.851110 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136]     if [ "${BASH_SOURCE-}" = "$0" ]; then
[Fri Jul 24 23:12:16.851170 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136]                            ^
[Fri Jul 24 23:12:16.851202 2020] [wsgi:error] [pid 30339] [remote 172.17.100.119:65136] SyntaxError: invalid syntax`

2. Here is wsgi_custom.py modified with correct directory
`import os
import sys

from django.core.wsgi import get_wsgi_application

exec(compile(open('/home/pyprojects/webvirtcloud/venv/bin/activate', "rb").read(), '/home/pyprojects/webvirtcloud/venv/bin/activate', 'exec'))

sys.path.append('/home/pyprojects/webvirtcloud')

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'webvirtcloud.settings')

application = get_wsgi_application()`

3. Here is virtual host configuration /etc/httpd/conf.d/virtualhost_webvirtcloud.conf
`<VirtualHost *:6080>
	ServerName djsvr.comhead.com.cn
	ServerAlias comhead.com.cn
	ServerAdmin xujianhua@comhead.com.cn
	
	DocumentRoot /home/pyprojects/webvirtcloud

	Alias /static /home/pyprojects/webvirtcloud/static
	Alias /media /home/pyprojects/webvirtcloud/media

	<Directory "/home/pyprojects/webvirtcloud/static">
		# AllowOverride None
		Require all granted
	</Directory>

	<Directory "/home/pyprojects/webvirtcloud/media">
		# AllowOverride None
		Require all granted
	</Directory>

	WSGIDaemonProcess webvirtcloud python-path=/home/pyprojects/webvirtcloud threads=2 maximum-requests=1000 display-name=webvirtcloud
	WSGIProcessGroup webvirtcloud

	WSGIScriptAlias / /home/pyprojects/webvirtcloud/webvirtcloud/wsgi_custom.py

	<Directory "/home/pyprojects/webvirtcloud/webvirtcloud">
		<Files "wsgi_custom.py">
			# AllowOverride None
			Require all granted
		</Files>
	</Directory>

</VirtualHost>`

**Comment by xujianhua1974** [comment]
2. Here is webvirtcloud/wsgi_custom.py modified with correct directory
`import os
import sys

from django.core.wsgi import get_wsgi_application
 
exec(compile(open('/home/pyprojects/webvirtcloud/venv/bin/activate', "rb").read(), '/home/pyprojects/webvirtcloud/venv/bin/activate', 'exec'))

sys.path.append('/home/pyprojects/webvirtcloud')
 
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'webvirtcloud.settings')

application = get_wsgi_application()`

**Comment by xujianhua1974** [comment]
2. Here is webvirtcloud/wsgi_custom.py modified with correct directory
	import os
	import sys
	from django.core.wsgi import get_wsgi_application
	exec(compile(open('/home/pyprojects/webvirtcloud/venv/bin/activate', "rb").read(), '/home/pyprojects/webvirtcloud/venv/bin/activate', 'exec'))
	sys.path.append('/home/pyprojects/webvirtcloud')
	os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'webvirtcloud.settings')
	application = get_wsgi_application()

**Comment by xujianhua1974** [comment]
3. Here is virtual host configuration /etc/httpd/conf.d/virtualhost_webvirtcloud.conf
	<VirtualHost *:6080>
		ServerName djsvr.comhead.com.cn
		ServerAlias comhead.com.cn
		ServerAdmin xujianhua@comhead.com.cn	
		DocumentRoot /home/pyprojects/webvirtcloud
		Alias /static /home/pyprojects/webvirtcloud/static
		Alias /media /home/pyprojects/webvirtcloud/media
		<Directory "/home/pyprojects/webvirtcloud/static">
			# AllowOverride None
			Require all granted
		</Directory>
		<Directory "/home/pyprojects/webvirtcloud/media">
			# AllowOverride None
			Require all granted
		</Directory>
		WSGIDaemonProcess webvirtcloud python-path=/home/pyprojects/webvirtcloud threads=2 maximum-requests=1000 display-name=webvirtcloud
		WSGIProcessGroup webvirtcloud
		WSGIScriptAlias / /home/pyprojects/webvirtcloud/webvirtcloud/wsgi_custom.py
		<Directory "/home/pyprojects/webvirtcloud/webvirtcloud">
			<Files "wsgi_custom.py">
				# AllowOverride None
				Require all granted
			</Files>
		</Directory>
	</VirtualHost>

**Comment by xujianhua1974** [comment]
@catborise : thanks for your attention!  please check these information I uploaded to guide me what possible root-cause may result in the error .

**Comment by catborise** [comment]
why are you using wsgi_custom?

have you see this doc : https://docs.djangoproject.com/en/3.0/howto/deployment/wsgi/modwsgi/
there is a snippet like that:
```
WSGIScriptAlias / /path/to/mysite.com/mysite/wsgi.py
WSGIPythonHome /path/to/venv
WSGIPythonPath /path/to/mysite.com

<Directory /path/to/mysite.com/mysite>
<Files wsgi.py>
Require all granted
</Files>
</Directory>
```

port 6080 is using for console access with no vnc.
gunicorn usually work with port 8000

**Comment by xujianhua1974** [comment]
@catborise: thanks. I have seen the docment you mentioned, but is different from my scenario. In my scenario, I deployed 3 Django WSGI applications in the same Apache instance. Each WSGI application needs its own Python virtual environmentuse different each other.  The WSGIPythonHome cannot be placed inside of the VirtualHost configuration because it applies to the whole Apache instance and not just the single VirtualHost according to mod_wsgi Documentation(release 4.7 [7.13.6 Embedded Mode (Multiple Applications)]), activation of the Python virtual environment needs to be performed in the WSGI script itself. So I used wsgi_custom.py (which is originated from webvirtcloud project code, and is suggested from webvirtcloud README.md as following:

`#### Apache mod_wsgi configuration`
`WSGIDaemonProcess webvirtcloud threads=2 maximum-requests=1000 display-name=webvirtcloud`
`WSGIScriptAlias / /srv/webvirtcloud/webvirtcloud/wsgi_custom.py`

**Comment by xujianhua1974** [comment]
@catborise: thanks.  I have changed to use wsgi.py, and using 8000 port, and I can open the login page. But I entered default admin user and password, and got a Internal Server Error (code 500). I checked the httpd error_log, it reported an error about sqlite3 writing a  readonly  database.

`[Sat Jul 25 10:03:03.183339 2020] [wsgi:error] [pid 18640] [remote 172.16.10.3:37602] mod_wsgi (pid=18640): Exception occurred processing WSGI script '/home/pyprojects/webvirtcloud/webvirtcloud/wsgi.py'.`
`[Sat Jul 25 10:03:03.194523 2020] [wsgi:error] [pid 18640] [remote 172.16.10.3:37602] Traceback (most recent call last):`
`[Sat Jul 25 10:03:03.194600 2020] [wsgi:error] [pid 18640] [remote 172.16.10.3:37602]   File "/home/pyprojects/webvirtcloud/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute`
`[Sat Jul 25 10:03:03.194613 2020] [wsgi:error] [pid 18640] [remote 172.16.10.3:37602]     return self.cursor.execute(sql, params)`
`[Sat Jul 25 10:03:03.194635 2020] [wsgi:error] [pid 18640] [remote 172.16.10.3:37602]   File "/home/pyprojects/webvirtcloud/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute`
`[Sat Jul 25 10:03:03.194645 2020] [wsgi:error] [pid 18640] [remote 172.16.10.3:37602]     return Database.Cursor.execute(self, query, params)`
`[Sat Jul 25 10:03:03.194686 2020] [wsgi:error] [pid 18640] [remote 172.16.10.3:37602] sqlite3.OperationalError: attempt to write a readonly database`
`[Sat Jul 25 10:03:03.194717 2020] [wsgi:error] [pid 18640] [remote 172.16.10.3:37602] `
`[Sat Jul 25 10:03:03.194727 2020] [wsgi:error] [pid 18640] [remote 172.16.10.3:37602] The above exception was the direct cause of the following exception:`

**Comment by catborise** [comment]
does httpd user has permission to write read webvirtcloud files? especially db.sqlite3?

**Comment by xujianhua1974** [comment]
@catborise: Thanks. I changed the webvirtcloud files ownership. And its work.
