### ISSUE TITLE
supervisord can't run 

### ISSUE THREAD

**Issue by xujianhua1974** [retspen/webvirtcloud#351]
I configured supervisord.conf as README.md in webvirtcloud, but I can't start supervisord, I got the following errors:
`8月 09 14:14:04 djsvr.comhead.com.cn supervisord[28533]: File "/usr/local/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in `
`8月 09 14:14:04 djsvr.comhead.com.cn supervisord[28533]: raise DistributionNotFound(req, requirers)`
`8月 09 14:14:04 djsvr.comhead.com.cn supervisord[28533]: pkg_resources.DistributionNotFound: The 'supervisor==3.1.4' distribution was not found and is`
`8月 09 14:14:04 djsvr.comhead.com.cn systemd[1]: supervisord.service: control process exited, code=exited status=1`
`8月 09 14:14:04 djsvr.comhead.com.cn systemd[1]: Failed to start Process Monitoring and Control Daemon.`

I have installed supervisor software using "yum install supervisor" 3.1.4, then I wanted to install supervisor using "pip install supervisor==3.1.4" and got the following errors 
ERROR: Command errored out with exit status 1:
     `command: /home/pyprojects/webvirtcloud/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-e6hmq5k0/supervisor/setup.py'"'"'; __file__='"'"'/tmp/pip-install-e6hmq5k0/supervisor/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-3f4xbhwo`
         `cwd: /tmp/pip-install-e6hmq5k0/supervisor/`
    `Complete output (2 lines):`
    `Supervisor requires Python 2.4 or later but does not work on any version of Python 3.  You are using version 3.7.6 (default, Feb 10 2020, 09:45:40)`
    `[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)].  Please install using a supported version.`
If I use "pip install supervisor" to install the latest supervisor, it can be installed without errors, but I can't still start supervisord daemon, with the same errors (It seems that supervisor version should be  3.1.4).

**Comment by catborise** [comment]
use pip3 to install supervisor, i think pip uses python2.
