### ISSUE TITLE
Don't run on debian :(

### ISSUE THREAD

**Issue by MaxPower87** [retspen/webvirtcloud#37]
Any idea how to get it run on debian?
I always get this error message when i try to start the application:

libxml2mod.so: undefined symbol: xmlOutputBufferGetContent

all demanded packages are installed (and even more):

libxml2:amd64                      2.8.0+dfsg1-7+wheezy4         amd64
libxml2-dbg:amd64                  2.8.0+dfsg1-7+wheezy4         amd64
libxml2-dev:amd64                  2.8.0+dfsg1-7+wheezy4         amd64
libxml2-utils                      2.8.0+dfsg1-7+wheezy4         amd64
libxml2-utils-dbg                  2.8.0+dfsg1-7+wheezy4         amd64
python-libxml2                     2.8.0+dfsg1-7+wheezy4         amd64
python-libxml2-dbg                 2.8.0+dfsg1-7+wheezy4         amd64
python-lxml                    2.8.0+dfsg1-7+wheezy4         amd64

**Comment by dubrsl** [comment]
Try to check if this symbol present in /usr/lib64/libxml2.so
# readelf -Ws /usr/lib64/libxml2.so | grep xmlOutputBufferGetContent
  1616: 0000000000064630    27 FUNC    GLOBAL DEFAULT   12 xmlOutputBufferGetContent@@LIBXML2_2.9.0

If not present, you need new libxml2

**Comment by MaxPower87** [comment]
ok thx for your help.
An upgrade to debian 8 (jessie) with move to systemd (libvirt won't run without systemd due to some dependencies) helped me out :)

**Comment by MaxPower87** [comment]
Ok now im facing the next issue :(
WebGUI is working, i can create Users, i can connect with my local KVM (Computes) and i can connect this Compute node with an instance.
But right after the connection i get the following error message:

![bildschirmfoto 2015-07-30 um 12 12 48](https://cloud.githubusercontent.com/assets/11743819/8980909/5a3934d4-36b4-11e5-926f-79cd012197a2.png)

**Comment by dubrsl** [comment]
So define the one storage pool. Go to Computer properties (Local)
http://<IP>/compute/1/storages/

**Comment by MaxPower87** [comment]
ok thx..im blind today...i wasn't aware that i can click an the Name of my new node ....*facepalm* :D
