### ISSUE TITLE
VM displayed in Instances page twice after 'unsafe' migration

### ISSUE THREAD

**Issue by wdhwang** [retspen/webvirtcloud#372]
Hi:
  I am trying migrate the VM 'cirros' from node1 to node2 with 'unsafe' option recently. The VM migration was successfully completed. But when I check instances status from the browser, I found there were two VM 'cirros' on the list with the same settings. The results was captured as the attachment picture. 
![question](https://user-images.githubusercontent.com/10345015/96106794-32224e80-0f0e-11eb-9e28-1057debc287b.png)

  Is there any solution for this situation?
  Thanks for your helping.

WD

**Comment by catborise** [comment]
Is there any special situation for using unsafe migration?
After migration completed, it is an option undefining source or not.

**Comment by wdhwang** [comment]
I am testing block migration on Ubuntu server. I found WebVirtCloud is so easy to install, configure and use. So I tested all function of WebVirtCloud in my environment. Because there is no shared storage in the environment, so I test VM migration with 'unsafe' option. Then the strange situation. migrated VM displayed in Instances page twice, was appeared. 
I even tried to remove the duplicate VM record from the table of 'instances_instance'. But that wasn't work, the record would insert into database again.
BTW, thanks for your response.

**Comment by catborise** [comment]
hi, i tested it again. there is not any problem with it. you should always check "Delete Original"="undefine source", if you do not have special purpose.

**Comment by wdhwang** [comment]
Hi, catborise:
  I enable the options of 'Unsafe live migration', 'Delete original', and the 'Instances' listing is ok now.
  Thanks for your helping.
![migrate](https://user-images.githubusercontent.com/10345015/96410522-a2d0b000-1219-11eb-995d-bebf7f5a2c9e.png)
