### ISSUE TITLE
Feature request: dynamic tokens for webvnc console link

### ISSUE THREAD

**Issue by lord-kyron** [retspen/webvirtcloud#374]
@Real-Gecko @catborise  - can you guys make the tokens on the webvnc console link (the token in the browser link) to STOP to be static (per vm) and to be generated automatically dinamic every time a new webvnc console is requested. This way it will prevent a person knowing the exact link (including the token) and open directly the vnc console. If it is dynamic - once you request a webvnc window (from the connect button) a new link and token are generated and once you close the window (the vnc connection) the old token have to expire. What do you think?

**Comment by lord-kyron** [comment]
@catborise - will this be something possible to implement?

**Comment by catborise** [comment]
uuid is primary key for instances. it could not change.
if someone has an user credentials he should access any instance. 

but there is a glitch i think. someone is not an admin but only a user. And it has a uuid info and host info. it could access someone's instance... i think it is a security issue. we should control if user has ownership or not...


nice catch... security issue...
we should provide a security to prevent that situation.

**Comment by lord-kyron** [comment]
Yes, that was what I meant when i opened this request. I already had traces in the past of someone trying to login on console of one of my VMs.

**Comment by catborise** [comment]
It is fixed . If someone is not owner of instance and not a superuser, cannot access Console even if he has uuid and host number
