### ISSUE TITLE
python requirements

### ISSUE THREAD

**Issue by catborise** [retspen/webvirtcloud#376]
@Real-Gecko hi,
there is some python modules in conf/requirements i dont know if they are necessary.
if they arent, can we remove them?

- beautifulsoup4
- numpy
- six
- zipp
- soupsieve
- sqlparse

**Comment by Real-Gecko** [comment]
These are dependencies of other packages. You can find which packages depend on which with pipdeptree https://pypi.org/project/pipdeptree/

**Comment by catborise** [comment]
i mean yes there are some dependencies but why we add them to requirements.txt, if it is dependant then it could install automatically.

**Comment by Real-Gecko** [comment]
I simply update requirements.txt with 'pip freeze > conf/requirements.txt' as it's what people usually do, sometimes you need to fix some dependency at certain version to avoid regression.
