### ISSUE TITLE
HTTP/500 on /console when instance uuid is changing

### ISSUE THREAD

**Issue by pznamensky** [retspen/webvirtcloud#379]
We've got lots of VMs which are recreating via our scripts or terraform.
That VMs preserve their names, but uuid changes each recreation.
One of the places where it breaks webvirtcloud is virtual console.
When VM is changing its uuid virtual console stops working and return 500 error.
As a workaround, we're deleting everything from table `instances_instance`, but it doesn't look very good :)
Is there any config parameter or something else which can help to fix the problem?

**Comment by catborise** [comment]
Yes that is a problem i knew it, but i forgot. A few times ago app was updating whenever is changed . But now it is not update it every time. It should be fixed. Otherwise it Requires manual db manipulation. 
@Real-Gecko  minimizing db calls operation occurs that. How we can solve it.

**Comment by Real-Gecko** [comment]
Can you please show exact error, with stacktrace if possible?

**Comment by pznamensky** [comment]
Thank you all for the quick reply.
>Can you please show exact error, with stacktrace if possible?

Unfortunately, I can't see the stacktrace although I have `Debug = True` in my config file (but it is possible that there are some issues in my setup though).

**Comment by catborise** [comment]
steps:
1. login webvirtcloud
2. open an instance console.
3. shutdown instance
4. go to host
4.1 copy instance xml
4.2. undefine instance
4.3 paste copied xml 
4.4 change only uuid
4.5. redefine instance and run it.
5. go to webvirtcloud try to open console
Result:
![image](https://user-images.githubusercontent.com/1725643/96699713-44314080-1397-11eb-9db1-5917d4742241.png)

**Comment by pznamensky** [comment]
Are there any chances it will be fixed? :)

**Comment by catborise** [comment]
@pznamensky i am not sure how to solve that problem. going back or different way...

i think we should solve it with bulk operations. otherwise query cost increase every listing time.
we can add a menu to refresh vm info, it updates database uuid...

**Comment by catborise** [comment]
@pznamensky i think problem is solved with adding uuid update...
please feedback.

thanks

**Comment by pznamensky** [comment]
@catborise thank you very much for the fix!
I'll check if everything works fine the next week

**Comment by pznamensky** [comment]
I can confirm, that we're able to connect to console now.
But I've noticed that after changing VMs uuid old records in `instances_instance` table are not updated and deleted.
Thus after changing uuid, new records are added.
Nevertheless, console is working fine now.
Thank you!

**Comment by catborise** [comment]
@pznamensky thanks. there was a problem with old record. i fixed it. i think this way is more apropriate. it deletes changed uuids and add new ones.

**Comment by pznamensky** [comment]
Thank you!
