### ISSUE TITLE
Question About Adding New Compute

### ISSUE THREAD

**Issue by leonyonz** [retspen/webvirtcloud#389]
Hello,

Is there any documentation for adding new compute ?

I mean, is the new compute need to full install like in README.MD

**Comment by catborise** [comment]
After minimal/server ubuntu/debian/Centos/fedora installation. You can run this script to prepare new compute.

https://github.com/retspen/webvirtcloud/blob/master/dev/libvirt-bootstrap.sh

Too see the operations you can look at details in this script .

You can also look at webvirtmgr(old version) wikis. Logic is same with webvirtcloud.
https://github.com/retspen/webvirtmgr/wiki

**Comment by leonyonz** [comment]
Thanks
