### ISSUE TITLE
No module named 'webvirtcloud.settings',when run 'docker build.......'command

### ISSUE THREAD

**Issue by lushtech** [retspen/webvirtcloud#395]
### 1 step: Run git clone
`git clone https://github.com/retspen/webvirtcloud.git`
### 2 step: Run docker build
` sudo docker build -t mywebvirtcloud    .`
**The error shows as blow when build running**
`Step 11/19 : RUN . venv/bin/activate &&     python3 manage.py migrate &&        chown -R www-data:www-data /srv/webvirtcloud
 ---> Running in 290a72712f56
Traceback (most recent call last):
 File "manage.py", line 21, in <module>
    main()
......

......

......
ModuleNotFoundError: No module named 'webvirtcloud.settings'
The command '/bin/sh -c . venv/bin/activate &&     python3 manage.py migrate &&         chown -R www-data:www-data /srv/webvirtcloud' returned a non-zero code: 1
`

**Comment by lushtech** [comment]
I copy the file webvirtcloud/settings.py.template  as settings.py, and set the SECRET_KEY, and the docker build work well.
And then running the container ok base on the image.
My suggestion: add a small section in the READ.md to tell people how to start it simply using docker.

**Comment by catborise** [comment]
There is a wiki page for docker/podman builds. As you Said we should add a reference to it
