### ISSUE TITLE
"There is an instance with same name. Remove it and try again!",when create a new VM in another computer.

### ISSUE THREAD

**Issue by lushtech** [retspen/webvirtcloud#396]
I control three computers by webvirtcloud. And some VM in every computer.But I cant create the same name VM in the diffirent computer.when I do it ,the error show:
There is an instance with same name. Remove it and try again!
----------------------------------------
**Is it a limitation in webvirtcloud that cant be same name VM in all computers?**

**Comment by catborise** [comment]
It should not be same vm names on the host. Probably you will confuse and will make mistakes. (Fatal mistakes) to prevent that we restricted same vm names.
If you create more than one instance with same name probably migration operations cause errors. Cannot migrate or cannot distinguish

**Comment by lushtech** [comment]
Thank you, I got it.
