### ISSUE TITLE
Possibility of using multiple connections to VMs simultaneously.

### ISSUE THREAD

**Issue by MagusRM** [retspen/webvirtcloud#403]
I'd like to offer possibility of using multiple connections to VMs simultaneously. libvirt-python [is thread safe](https://wiki.libvirt.org/page/FAQ#Is_libvirt_thread_safe.3F), why [wvmConnection](https://github.com/retspen/webvirtcloud/blob/9aed7c771603dba65739f47508a976fa0ef63216/vrtManager/connection.py#L46) shouldn't?

**Comment by catborise** [comment]
what do you mean for that propose? 
access vm console with multiple user?

**Comment by MagusRM** [comment]
@catborise , in my project I needed to revert several VMs in several threads. Since using of wvmConnection in several threads simultaneously isn't thread safe I cannot do that using threads (yeah I realized I can do it with asyncio, but maybe making of wmvConnection thread safe still would be greate).

**Comment by MagusRM** [comment]
@catborise  , I'm newbie in libvirt and webvirtcloud, so I don't have in depth understanding of both. Now I did some research and understood that my proposal (that I couldn't explain clearly) is already implemented. Sorry for wasting your time:(

If you are interested, I tried to propose possibility of using single connection to libvirtd by several threads. (Hope now explanation is better)
