### ISSUE TITLE
broken python dependency

### ISSUE THREAD

**Issue by gr4yj3d1** [retspen/webvirtcloud#419]
Hi,
when following the installations steps for ubuntu on debian/sid I got an error at the `pip install -r conf/requirements.txt` step

   ```
 Complete output (13 lines):
    running install
    running build
    /usr/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
    /srv/webvirtcloud/venv/bin/python generator.py libvirt /usr/share/libvirt/api/libvirt-api.xml
    Found 480 functions in /usr/share/libvirt/api/libvirt-api.xml
    Found 0 functions in libvirt-override-api.xml
    Generated 389 wrapper functions
    Missing type converters:
    char ** *:1
    char **:1
    ERROR: failed virDomainAuthorizedSSHKeysGet
    ERROR: failed virDomainAuthorizedSSHKeysSet
    error: command '/srv/webvirtcloud/venv/bin/python' failed with exit code 1
```

###  suggested solution
when I bumped version of libvirt-python in requirements.txt from 6.9.0 to the current 7.1.0 the Error message went away

possibly related: [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=982695](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=982695)

**Comment by catborise** [comment]
@gr4yj3d1 thanks. it is updated and commited.
