### ISSUE TITLE
Instance Detail only show power on

### ISSUE THREAD

**Issue by Mooseclown** [retspen/webvirtcloud#429]
Hi,
I install webvirtcloud on CentOS 7 and everything is good.
But in the instance detail, I can't change tab when I click all the buttons.
Can you help me?

Thanks for your feedback.

**Comment by Mooseclown** [comment]
like this
the url is 192.168.77.157/instances/1/#access
but the tab still at "Power"
![image](https://user-images.githubusercontent.com/39301465/116512814-2ec74100-a8fb-11eb-840c-3143d84f9053.png)

**Comment by catborise** [comment]
It is unknown situation. Can you look at the browser console if there is any error.
You should navigate all tabs, it is not related with instance power state.

**Comment by Mooseclown** [comment]
Thank you, I found that it was a problem with SElinux.
