### ISSUE TITLE
vGPU

### ISSUE THREAD

**Issue by tree1123** [retspen/webvirtcloud#435]
how can i set vGPU?  does someone has idea?

**Comment by catborise** [comment]
you should add it with virt-manager. 
not implemented at webvirtcloud.

**Comment by tree1123** [comment]
> you should add it with virt-manager.
> not implemented at webvirtcloud.

thank you. 
can i  build a  instance in webvirtcloud, than  add gpu with virt-manager?
which document i can read?

**Comment by catborise** [comment]
using webvirtcloud, you can list, create, update, manage, delete instances. 
you can manage multiple hypervisor hosts. 
it is simple application. 
it is a web ui alternative for virt-manager.

yes u can create instance with webvirtcloud then edit with virt-manager to add vgpu.
webvirtcloud and virt-manager is a ui for libvirt.
libvirt is an api for managing kvm/xen/hyperv hypervisors.
normally libvirt has own tool which is “virsh”. but it is a command line application. webvirtcloud eases libvirt usage.

you should read libvirt/virt-manager/kvm related articles to understand the concept.

**Comment by tree1123** [comment]
> using webvirtcloud, you can list, create, update, manage, delete instances.
> you can manage multiple hypervisor hosts.
> it is simple application.
> it is a web ui alternative for virt-manager.
> 
> yes u can create instance with webvirtcloud then edit with virt-manager to add vgpu.
> webvirtcloud and virt-manager is a ui for libvirt.
> libvirt is an api for managing kvm/xen/hyperv hypervisors.
> normally libvirt has own tool which is “virsh”. but it is a command line application. webvirtcloud eases libvirt usage.
> 
> you should read libvirt/virt-manager/kvm related articles to understand the concept.

thank you.
i know.i will try.
