### ISSUE TITLE
Hardcoded websocket path when using noVNC full version

### ISSUE THREAD

**Issue by wongsyrone** [retspen/webvirtcloud#440]
I have to change ws_path everytime when I want to use noVNC full variant.

Hardcoded here:
https://github.com/retspen/webvirtcloud/blob/a20fa8e8d76a442ea4225c469d7666aab5b15e8d/console/templates/console-vnc-full.html#L221-L222

The lite version works because:
https://github.com/retspen/webvirtcloud/blob/a20fa8e8d76a442ea4225c469d7666aab5b15e8d/console/templates/console-vnc-lite.html#L177-L178

get data from:

https://github.com/retspen/webvirtcloud/blob/a20fa8e8d76a442ea4225c469d7666aab5b15e8d/console/views.py#L74-L87

**Comment by wongsyrone** [comment]
The issue is caused by https://github.com/retspen/webvirtcloud/commit/43f1461e299fecb72fe05958d37c33702c3dbe94

**Comment by wongsyrone** [comment]
@catborise @retspen The template got removed from the commit above. Is it intentional?

**Comment by catborise** [comment]
I dont think it is intentional change, may be it is missed. We could change it, if it is useful.

**Comment by wongsyrone** [comment]
I think it's useful as it's more convenient.

**Comment by wongsyrone** [comment]
@catborise Any update on this?

**Comment by catborise** [comment]
@wongsyrone it is initiated at different place. changing "websockify" does not affect. i think it is set in UI.js which is not reach ws_path value.

**Comment by wongsyrone** [comment]
@catborise 

Nope. I fixed it on my side by reverting partial changes (console-vnc-full.html) of https://github.com/retspen/webvirtcloud/commit/43f1461e299fecb72fe05958d37c33702c3dbe94

**Comment by catborise** [comment]
@wongsyrone i change it. but i cannot test it(my test shows no effect). if it is working fine...

**Comment by wongsyrone** [comment]
https://github.com/retspen/webvirtcloud/commit/24cd3f70ddefe529b97e019fa46c54180c64b725 looks good to me.

**Comment by MisterBlueBear** [comment]
I don't think this fix works at all. If I view the HTML source, I do see the correct HTML code, but in the console settings, it is still set to "websockify".

May I suggest just adding the location conf for "**websockify**" to /etc/nginx/conf.d/webvirtcloud.conf as a workaround. This fixes the issue.

```
    location /websockify {
        proxy_pass http://wssocketiod;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
```
