### ISSUE TITLE
302 TOO MANY REDIRECTS ?

### ISSUE THREAD

**Issue by ochbob** [retspen/webvirtcloud#453]
Hello,

I have exactly the same issue as #431 

I'm running Debian 11, and I have installed webvirtcloud mannually.
My old webvirtcloud setup is working great, but I would like to update it with the latest commit.

Install from scratch is OK, everything seems up and running:

```
gstfsd                           RUNNING   pid 1700955, uptime 0:00:05
novncd                           RUNNING   pid 1700956, uptime 0:00:05
webvirtcloud                     RUNNING   pid 1700957, uptime 0:00:05
```

but I got 302 error and I can't figure out what's the issue (not really explaned in the previous issue)

Here my old python package requirement where my setup is working fine on my system:

Django==2.2.20
django-bootstrap4==3.0.0
django-icons==3.0.0
django-login-required-middleware==0.5.0
django-otp==1.0.2
django-qr-code==1.3.1
gunicorn==20.1.0
libsass==0.20.1
libvirt-python==7.2.0
lxml==4.6.3
qrcode==6.1
rwlock==0.0.7
websockify==0.9.0
zipp==3.4.0

Any ideas ? Is this related to django packages version which are more recent ?
(I tried to dowgrade django-otp 1.0.6 to 1.0.2 as my running version, but no chance )

Thank you !

**Comment by catborise** [comment]
is debian 11 released?
on debian 10 running smoothly. but we havent not test on it 11. it is i think rc state...

**Comment by ochbob** [comment]
Not yet officially. But webvirtcloud works great on my Debian 11 with my old folder installation.

**Comment by ochbob** [comment]
It was an issue in my settings.py...
I was using the old one... with a bootstrap4.

Everythings works great !
