### ISSUE TITLE
Hypervisor doesn't have any Flavors

### ISSUE THREAD

**Issue by DaemonWalker** [retspen/webvirtcloud#461]
I delete all Flavors at create instance page, how do I create a new flavors now?
![image](https://user-images.githubusercontent.com/16376560/132228195-0d833e34-be9e-4e4d-8976-f864252b22d8.png)

**Comment by catborise** [comment]
hmm it is a bug :) there should be a button to add beside warning.

we were adding it with code initialization. i will add a button to add a flavor

**Comment by DaemonWalker** [comment]
Oh,  thanks a lot!

**Comment by catborise** [comment]
yes it can be added to db. but i add button to add new flavour if there is not any
