### ISSUE TITLE
Can not upload iso file to Storage: iso

### ISSUE THREAD

**Issue by hiepvq** [retspen/webvirtcloud#476]
HI

before i installed it work fines, but now i reinstall i got this error. you can solve this problem?

![Screenshot 2021-12-17 073110](https://user-images.githubusercontent.com/36187674/146469200-8c2e6807-7fa0-4555-a280-93d80feae23e.png)

**Comment by catborise** [comment]
@hiepvq  it should be fixed now. I cannot tested please feedback

**Comment by hiepvq** [comment]
@catborise thank you, now it works fine
