### ISSUE TITLE
HOW TO UNINSTALL WEBVIRTCLOUD?

### ISSUE THREAD

**Issue by Wotan6891** [retspen/webvirtcloud#495]
Hello,

for reasons of lack of capacity of my pc, I have to remove webvirtcloud.

I have an Ubuntu machine.

how to uninstall it?

Thank you

**Comment by catborise** [comment]
webvirtcloud is a small application. it does not much effect on storage. it about 500mb to 700mb with all libraries.
may be you want to delete a virtual machine?

**Comment by Wotan6891** [comment]
hello,
thanks for your answer.

the problem was the port it used, and that port is used by another application.

I had to delete the files. but I never found a way to remove it by terminal.

**Comment by lmsdscav** [comment]
delete its supervior service and nginx web config. Then the port'll be free. :)

**Comment by lmsdscav** [comment]
/etc/supervisor/   ()
and /etc/nginx/conf.d/ ()
