### ISSUE TITLE
It could work with Proxmox VE?

### ISSUE THREAD

**Issue by gilbertoferreira** [retspen/webvirtcloud#517]
Hello there.
First of all I wanna thank you for this wonderful piece of software.
Is there any change to this software works with Proxmox VE?
Thanks

**Comment by catborise** [comment]
hi, thanks. i havent tested it but it should be working together. because both of them use libvirt+connect mechanism.
i wonder that why would you use both of them. proxmox is similar with webvirtcloud.

**Comment by gilbertoferreira** [comment]
It's some sort of.
AFAIK Proxmox doesn't use libvirt, just qemu/kvm and lxc.

**Comment by catborise** [comment]
sorry my mistake, proxmox is using directly qemu/kvm toolkits. 
libvirt is a sidekick. so, they should work together. eventually libvirt is working like a wrapper, but it think they isolate resources to prevent manage them.

**Comment by gilbertoferreira** [comment]
So how can we do webvirtcloud work with Proxmox?
I am not a developer but I am willing to do whatever is possible to do that.
Just send me patch instructions etc I will do so.

**Comment by catborise** [comment]
i want to learn what is the motivation. why you want to stick with proxmox and do not want to use their interface. 
Why dont you use webvirtcloud + qemu/kvm combination to manage your virtual machines?

**Comment by gilbertoferreira** [comment]
> i want to learn what is the motivation. why you want to stick with proxmox and do not want to use their interface. Why dont you use webvirtcloud + qemu/kvm combination to manage your virtual machines?

Well... I am more interested in the interface to access the VM itself. I mean it just like WHMCS or some sort of.
Proxmox is great in admin point of view, but lack a nice interface for a enduser which contract a VPS on top of Proxmox for instance. You got it?

**Comment by carlosjs23** [comment]
@gilbertoferreira Proxmox does have an API so if you want to build something on top of it you certainly can.
I use Proxmox and I give my clients Proxmox access with a limited user to his resources, if you want to have a better UI you can ditch Proxmox and move to something like this that's easier to build on or stick with Proxmox and use it's API.

**Comment by gilbertoferreira** [comment]
ok
