### ISSUE TITLE
No module name django

### ISSUE THREAD

**Issue by tboulogne** [retspen/webvirtcloud#52]
Hello,

I setup webvirtcloud easily but i face a problem with console
I obviously get this error (Server disconnected (code: 1006)). Looking at novncd log :
````
Traceback (most recent call last):
  File "/srv/webvirtcloud/console/novncd", line 6, in <module>
    import django
ImportError: No module named django
````

Seems django not installed in the virtualenv.

Any tips to solve this please ?

Thank :-)

**Comment by tboulogne** [comment]
[UPDATE 1]
it was a permission problem. Could not simply make a 
``
pip install -r conf/requirements.txt
``
in /srv/webvirtcloud directory. All things are not installed in the virtuaIenv. I make a 777 for setup and setting back permission after. It's works.

[UPDATE 2]
Dismiss any error message in novnc log, but not working. I omit to say that i activate https to access interface. Reverting back to http, novnc work. Question : where could i find nonvc port management please ?

**Comment by savichev** [comment]
https://github.com/retspen/webvirtcloud/issues/46#issuecomment-130535461

**Comment by savichev** [comment]
You need the corresponding file in root "webvirtcloud" with name cert.pem

**Comment by tboulogne** [comment]
Hello thanks for your answer. Works great :-). :+1:

**Comment by savichev** [comment]
You're welcome
