### ISSUE TITLE
Base64 issue in docker image with latest Dockerfile

### ISSUE THREAD

**Issue by 5he1n** [retspen/webvirtcloud#525]
Due to usage of **phusion/baseimage:jammy-1.0.0** for Dockerfile (de-facto Ubuntu 22.04) - default python version is **3.10** which causes problems for SSH key addition in profile page:
```
AttributeError at /accounts/ssh_key/create/

module 'base64' has no attribute 'decodestring'
```
In base64 module decodestring & encodestring functions are available for python < 3.9.

**Comment by catborise** [comment]
i convert decodestring to decodebytes because of depreciation. it should be worked. i tested. it is working.
