### ISSUE TITLE
libvirt Error - Hook script execution failed

### ISSUE THREAD

**Issue by CanGoymen** [retspen/webvirtcloud#536]
When I try to activate second virtual machine than this error occurs:

libvirt Error - Hook script execution failed: internal error: Child process (LC_ALL=C PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin /etc/libvirt/hooks/qemu test prepare begin -) unexpected exit status 1

![Screen Shot 2022-09-06 at 23 21 20](https://user-images.githubusercontent.com/49080219/188731078-1880c013-eba7-4837-8b9f-d14a961fa3ed.png)

![Screen Shot 2022-09-06 at 23 19 26](https://user-images.githubusercontent.com/49080219/188730618-3684aa42-f950-4458-8227-1aae7ad8df75.png)

virt-host-validate result:
<img width="989" alt="image" src="https://user-images.githubusercontent.com/49080219/188731236-dc840a78-ba54-4119-9072-4127824a4ad8.png">

**Comment by catborise** [comment]
do you test it with virt-manager? i think it is related with libvirt bug, but you should test it with virt-manager to see if it is working or not.

**Comment by CanGoymen** [comment]
I have figured it out , the problem was caused by /etc/libvirt/qemu file.  qemu looks /run/xtables.lock file, but file's permission was wrong. I gave 777 than resolved.

sudo chmod 777 xtables.lock

Thanks.
