### ISSUE TITLE
cannot access to instances, and poweroff not work

### ISSUE THREAD

**Issue by xiedeacc** [retspen/webvirtcloud#547]
![image](https://user-images.githubusercontent.com/8072296/194732209-8f465bb0-979f-4297-9c6f-97fe78c4b73c.png)

**Comment by xiedeacc** [comment]
it seems webvirtcloud didn't install os to instance at all, duplicated with https://github.com/retspen/webvirtcloud/issues/548, so I closed this issue

**Comment by catborise** [comment]
may be it is a firewall blocking. which ports do you using for console. 6080? is it open?
