### ISSUE TITLE
webvirtcloud cannot install os to instance

### ISSUE THREAD

**Issue by xiedeacc** [retspen/webvirtcloud#548]
I followed this post to install webvirtcloud https://techviewleo.com/install-webvirtcloud-kvm-web-dashboard-on-ubuntu/, but I cannot see virtual instance by console, I think webvirtcloud didn't boot from cd-rom at all, how to install a os to instance? or what's problem?

my host is ubuntu22.04 server version,
and I want instance install ubuntu22.0 server version

**Comment by xiedeacc** [comment]
my host is ubuntu22.04 server,
and I want instance install ubuntu22.0 server

**Comment by xiedeacc** [comment]
it seems webvirtcloud's bug,  I manual installed create a os by use virt-install command

virt-install \
 --name tiger_1 \
 --description "ubuntu 22.04" \
 --os-type=Linux \
 --os-variant=ubuntu22.04 \
 --ram=4096 \
 --vcpus=2 \
 --disk path=/data1/virt/image/tiger_1.img,bus=virtio,size=60 \
 --network bridge=br0 \
 --graphics none \
 --console pty,target_type=serial \
 --location /data1/virt/iso/ubuntu-22.04.1-live-server-amd64.iso,kernel=casper/vmlinuz,initrd=casper/initrd \
 --extra-args 'console=ttyS0,115200n8'

**Comment by xiedeacc** [comment]
@catborise can U cc this problem?

**Comment by catborise** [comment]
i tested it again. it is working as expected. you missing some steps. 
did you add iso pool?
![image](https://user-images.githubusercontent.com/1725643/194817199-71368dcb-a1e5-432b-b4f1-901220cb3475.png)
do you see isos in iso pool:
![image](https://user-images.githubusercontent.com/1725643/194817322-432acc3f-371e-46fe-a933-e267533f3854.png)

did you mount iso to instance?
![image](https://user-images.githubusercontent.com/1725643/194817535-5e4e75b2-2732-422c-ac7b-3f94c45fadac.png)

if instance was booted before, you must enable boot and set boot order like;
![image](https://user-images.githubusercontent.com/1725643/194817780-0c5bd79d-1a82-4312-bdb2-2fda47954fcf.png)

**Comment by xiedeacc** [comment]
ok, I will check it
