### ISSUE TITLE
webvirtcloud cannot access to instance

### ISSUE THREAD

**Issue by xiedeacc** [retspen/webvirtcloud#549]
my host and instance os all is ubuntu server22.04. webvirtcloud can start and shutdown instance, but cannot access to instance by console, use virsh console and ssh can connect to instance, so I guess webvirtcloud doesn't get instance's ip address? it's right? 

from this picture, we can see instance get a ip address from route via bridge on host os
![image](https://user-images.githubusercontent.com/8072296/194749135-00cb3ee1-c0a1-4169-9e83-0fc719e5571f.png)

from this picture, we can see webvirtcloud didn't get ip address from instance? does webvirtcloud only support static address, or other bug?
![image](https://user-images.githubusercontent.com/8072296/194749234-477212a5-40fc-4e0c-bc7a-e46e488ea349.png)

**Comment by catborise** [comment]
it is not related with ip address.. console does not use tcp protocol.
if you want to see ip address of instance from webvirtcloud. you must enable qemu-guest-agent socket:
![image](https://user-images.githubusercontent.com/1725643/194815748-a264d710-7ec3-4ee9-b9c6-806aceb3c403.png)

then you must install and start qemu-agent to instance os.

**Comment by xiedeacc** [comment]
ok, I think webvirtcloud should provide a user manual....@catborise
