### ISSUE TITLE
Gunicorn defunct process ?

### ISSUE THREAD

**Issue by qwrty-ftw** [retspen/webvirtcloud#558]
Hello, 

I just upgrade my webvirtcloud instance three days ago and I notice some weird defunct process just after launching supervisord:

> www-data 3204598       1  0 Nov20 ?        00:00:29 /opt/webvirtcloud/venv/bin/python /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
> www-data 3204599 3204598  0 Nov20 ?        00:00:07 /opt/webvirtcloud/venv/bin/python /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
> www-data 3204605 3204598  0 Nov20 ?        00:00:00 /opt/webvirtcloud/venv/bin/python /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
> www-data 3204606 3204599  0 Nov20 ?        00:00:00 [bash] <defunct>
> www-data 3204611 3204605  0 Nov20 ?        00:00:00 [bash] <defunct>
> www-data 3204616 3204598  0 Nov20 ?        00:00:00 /opt/webvirtcloud/venv/bin/python /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
> www-data 3204618 3204598  0 Nov20 ?        00:00:00 /opt/webvirtcloud/venv/bin/python /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
> www-data 3204626 3204598  0 Nov20 ?        00:00:00 /opt/webvirtcloud/venv/bin/python /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
> www-data 3204627 3204598  0 Nov20 ?        00:00:00 /opt/webvirtcloud/venv/bin/python /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
> www-data 3204628 3204598  0 Nov20 ?        00:00:00 /opt/webvirtcloud/venv/bin/python /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
> www-data 3204631 3204616  0 Nov20 ?        00:00:00 [bash] <defunct>
> www-data 3204636 3204598  0 Nov20 ?        00:00:07 /opt/webvirtcloud/venv/bin/python /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
> www-data 3204637 3204618  0 Nov20 ?        00:00:00 [bash] <defunct>
> www-data 3204642 3204626  0 Nov20 ?        00:00:00 [bash] <defunct>
> www-data 3204647 3204627  0 Nov20 ?        00:00:00 [bash] <defunct>
> www-data 3204652 3204598  0 Nov20 ?        00:00:07 /opt/webvirtcloud/venv/bin/python /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
> www-data 3204653 3204598  0 Nov20 ?        00:00:00 /opt/webvirtcloud/venv/bin/python /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
> www-data 3204655 3204636  0 Nov20 ?        00:00:00 [bash] <defunct>
> www-data 3204663 3204598  0 Nov20 ?        00:00:07 /opt/webvirtcloud/venv/bin/python /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
> www-data 3204664 3204652  0 Nov20 ?        00:00:00 [bash] <defunct>
> www-data 3204669 3204653  0 Nov20 ?        00:00:00 [bash] <defunct>
> www-data 3204675 3204663  0 Nov20 ?        00:00:00 [bash] <defunct>
> www-data 3204680 3204598  0 Nov20 ?        00:00:00 /opt/webvirtcloud/venv/bin/python /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
> www-data 3204681 3204598  0 Nov20 ?        00:00:00 /opt/webvirtcloud/venv/bin/python /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
> www-data 3204683 3204628  0 Nov20 ?        00:00:00 [bash] <defunct>
> www-data 3204690 3204680  0 Nov20 ?        00:00:00 [bash] <defunct>
> www-data 3204695 3204598  0 Nov20 ?        00:00:07 /opt/webvirtcloud/venv/bin/python /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
> www-data 3204696 3204681  0 Nov20 ?        00:00:00 [bash] <defunct>
> www-data 3204702 3204598  0 Nov20 ?        00:00:00 /opt/webvirtcloud/venv/bin/python /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
> www-data 3204705 3204598  0 Nov20 ?        00:00:07 /opt/webvirtcloud/venv/bin/python /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
> www-data 3204706 3204702  0 Nov20 ?        00:00:00 [bash] <defunct>
> www-data 3204707 3204598  0 Nov20 ?        00:00:00 /opt/webvirtcloud/venv/bin/python /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
> www-data 3204712 3204705  0 Nov20 ?        00:00:00 [bash] <defunct>
> www-data 3204717 3204707  0 Nov20 ?        00:00:00 [bash] <defunct>
> www-data 3204724 3204695  0 Nov20 ?        00:00:00 [bash] <defunct>
> www-data 3207256 3207241  0 Nov20 ?        00:00:13 /opt/webvirtcloud/venv/bin/python3 /opt/webvirtcloud/console/novncd
> www-data 3207258 3207256  0 Nov20 ?        00:00:00 [bash] <defunct>

pstree view:

`|-gunicorn /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
  |   |-gunicorn /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
  |   |   |-(bash)
  |   |   `-{gunicorn}
  |   |-gunicorn /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
  |   |   |-(bash)
  |   |   `-{gunicorn}
  |   |-gunicorn /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
  |   |   |-(bash)
  |   |   `-{gunicorn}
  |   |-gunicorn /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
  |   |   |-(bash)
  |   |   `-{gunicorn}
  |   |-gunicorn /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
  |   |   |-(bash)
  |   |   `-{gunicorn}
  |   |-gunicorn /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
  |   |   |-(bash)
  |   |   `-{gunicorn}
  |   |-gunicorn /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
  |   |   |-(bash)
  |   |   `-{gunicorn}
  |   |-gunicorn /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
  |   |   |-(bash)
  |   |   `-{gunicorn}
  |   |-gunicorn /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
  |   |   |-(bash)
  |   |   `-{gunicorn}
  |   |-gunicorn /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
  |   |   |-(bash)
  |   |   `-{gunicorn}
  |   |-gunicorn /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
  |   |   |-(bash)
  |   |   `-{gunicorn}
  |   |-gunicorn /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
  |   |   |-(bash)
  |   |   `-{gunicorn}
  |   |-gunicorn /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
  |   |   |-(bash)
  |   |   `-{gunicorn}
  |   |-gunicorn /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
  |   |   |-(bash)
  |   |   `-{gunicorn}
  |   |-gunicorn /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
  |   |   |-(bash)
  |   |   `-{gunicorn}
  |   |-gunicorn /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
  |   |   |-(bash)
  |   |   `-{gunicorn}
  |   `-gunicorn /opt/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /opt/webvirtcloud/gunicorn.conf.py
  |       |-(bash)
  |       `-{gunicorn}`

Gunicorn conf: https://justpaste.it/cf0zk
Debian 11 with nginx version: nginx/1.18.0

Any ideas ?

Thank you !

**Comment by ochbob** [comment]
Same as #559

**Comment by qwrty-ftw** [comment]
Closed since merge #562

**Comment by qwrty-ftw** [comment]
Closed since merge #562
