### ISSUE TITLE
Disk pool and network selection non-response

### ISSUE THREAD

**Issue by CensorKo** [retspen/webvirtcloud#566]
No response when click add image and add network button in custom instance.

Occurs on: 711870b5a123638da02a1e089fe1b36d1b352b72
Safari and Chrome are both not working.
Ubuntu server 20.04

But working on: fea1571e1a0d02fc95be5b7bb9bffcf1af490518

![notworking-webvirt](https://user-images.githubusercontent.com/37770223/215306622-c72fa6ce-4e19-42d1-930c-7f8577a08f04.png)

**Comment by catborise** [comment]
thanks. it is fixed. it is related with old bootstrap js commands...
