### ISSUE TITLE
Setting up a VM with ubuntu 20.04

### ISSUE THREAD

**Issue by nadermx** [retspen/webvirtcloud#580]
I was able to get everything working, and thanks to your help from the networking issue I added that.  What I seem to struggle with, is the only thing I can find about how to set up a ubuntu VM or a Centos, or what not is this, https://github.com/retspen/webvirtcloud/issues/548 and that seems slightly confusing.

Is there any way I could get a quick rundown on what I should do after I connect the compute, set up the networking.  How do I actually get a iso of ubuntu on a vm?  I set up these storages 
![image](https://user-images.githubusercontent.com/7340380/233509044-c87189cd-3dd1-4ad0-8775-6276fa698e44.png)
but I feel I am missing another storage. 

And I am unsure if on the host I need to download the ubuntu iso to clone intwo a qcow directory, or can I use one of the existing flavors from here?
![image](https://user-images.githubusercontent.com/7340380/233509212-9d64073b-6568-4678-9d8d-b18ab3422d3c.png)
And then switch the ubuntu iso into it?

Do I have to download the ubuntu-server 20-04 from ubuntu ontop the host and move it to a specific directory?

Thank you in advance

**Comment by catborise** [comment]
1. Download ubuntu iso from ubuntu web site.
2. Copy os iso image to iso repository.
3. Create an instance from flavor.
4. Attach iso to instance cd-rom
5. make cdrom first on boot menu.
6. Start instance.
7. open console.
8. install operating system as usual.
9. if you want you can make this instance a template. whenever you need clone/create instance from the template.

**Comment by nadermx** [comment]
I get stuck on step 6 with this error 
![image](https://user-images.githubusercontent.com/7340380/233667661-192d2a3e-7417-43ec-b9c1-046238b09a4a.png)
but on the host when I run this, I see this 
![image](https://user-images.githubusercontent.com/7340380/233667444-40dc167e-5336-48e7-acc3-b131aee81762.png)
and the admin of webvirt shows this
![image](https://user-images.githubusercontent.com/7340380/233667780-482a6306-2d52-4a48-80fb-013d9a94639a.png)
I feel I am close, and appreciate your help

**Comment by nadermx** [comment]
I was able to fix it, because I Remember some where either you or some one said the bridge had to be the same name as the network, so I remade a bridge called the same as my default `virbr0`
![image](https://user-images.githubusercontent.com/7340380/233673529-ff16e853-f688-4720-be9e-9e15ce833c86.png)
