### ISSUE TITLE
CentOS 6:No useable disks have been found

### ISSUE THREAD

**Issue by xiaoqian2006** [retspen/webvirtcloud#591]
I basically went to install a centos6 with the default configuration, but came across the following
![image](https://github.com/retspen/webvirtcloud/assets/40530007/b77bdf61-509b-4e15-b533-1ef7d5c27382)
![image](https://github.com/retspen/webvirtcloud/assets/40530007/996bb20f-e05f-4f1c-a8bd-2eb2761d28e7)
![image](https://github.com/retspen/webvirtcloud/assets/40530007/bf007816-c6cb-47b7-b67a-895ec493be81)

**Comment by catborise** [comment]
it seems centos6 does not suport virtio bus. then you must choose ide or scsi bus
![image](https://github.com/retspen/webvirtcloud/assets/1725643/049f49cf-1e18-43c4-a927-ee3a68cb37d8)
steps;
1. shutdown instance
2. detach all disks
3. add disk - existing disk.
4. choose bus as scsi
5. add

![image](https://github.com/retspen/webvirtcloud/assets/1725643/fb00eab6-1d76-4e06-981c-43b30e503d93)

**Comment by xiaoqian2006** [comment]
I have tried both ide and scsi, scsi is still undetectable, but ide boots up with the error "unsupported configuration: IDE controllers are unsupported for this QEMU binary or machine type", I looked on the net and it says to use sata bus, so far it works!
