### ISSUE TITLE
CentOS6:No ifcfg-eth0.

### ISSUE THREAD

**Issue by xiaoqian2006** [retspen/webvirtcloud#592]
I didn't detect the NIC after installing CentOS6 following the default steps.

![image](https://github.com/retspen/webvirtcloud/assets/40530007/28e6ed39-b02d-43f3-b50f-0e49f408d0bb)

The network card is configured as follows：

![image](https://github.com/retspen/webvirtcloud/assets/40530007/3773c964-5032-49e9-bc69-dc6680e71508)

While installing it, I noticed a little difference and the picture above the net：

![image](https://github.com/retspen/webvirtcloud/assets/40530007/c393ad4a-8baf-4675-a36c-bfd9e2b70191)

**Comment by catborise** [comment]
for now changing model of network card is not possible with the help of a dropbox, but you can change it manually. edit xml of instance. change model type of network card to "e1000e"
from
![image](https://github.com/retspen/webvirtcloud/assets/1725643/2a72f285-4e4d-4c17-a1e9-a9d3d3c22e87)
to:
![image](https://github.com/retspen/webvirtcloud/assets/1725643/9365bf7f-c54b-44e8-9c20-27fdb957c190)

**Comment by xiaoqian2006** [comment]
After the modification, the execution of `ip addr` can see the network card, but ifcfg-eth0 is not generated, so I manually added up, in addition to the UUID is not added, the parameters have all the parameters, but does not seem to work!

![image](https://github.com/retspen/webvirtcloud/assets/40530007/e9fd030d-1186-478e-b9e5-93a602f589d4)

I chose to recreate a VM instance , change the NIC configuration before the iso bootloader executes, and it worked!

![image](https://github.com/retspen/webvirtcloud/assets/40530007/ab5ec321-9b6d-4ce9-be98-6fed00f53815)

**Comment by xiaoqian2006** [comment]
@catborise Thanks for the answer, CentOS6 is now fully installed!
