### ISSUE TITLE
IP address assignment question

### ISSUE THREAD

**Issue by amarc** [retspen/webvirtcloud#6]
So let's say I have server with 7 IP addresses routed to me. They are in no way dependant on server and it's interface/ip/mac. 

How would I create network for this? I tried bridge, making my server IP be br0 but networking on guest machine (and with one IP from these 7) is not working. 

ty.

**Comment by chamambom** [comment]
i am sure its the same way you do it on webvirtmgr , this is what you can do .....create a bridge that is tied to the host physical interface and that bridge will have something like 192.168.1.1/29 and when you create your network using the webvirtcloud web GUI ,select bridge and copy the name of the bridge under interfaces and you are done

**Comment by amarc** [comment]
Managed it somehow with bridge networking. Closing
