### ISSUE TITLE
Update Installer Script for Debian 12 Dependencies

### ISSUE THREAD

**Issue by ShengruiZhang** [retspen/webvirtcloud#601]
I was trying to install WebVirtCloud on a headless Debian 12, and encountered dependency issues.

After investigation, it appears that the Beta Installer doesn't install the following packages and thus causes issues during installation.
`libsasl2-dev libldap2-dev`

https://github.com/retspen/webvirtcloud/blob/ca54ae0c653f5872989b7c40dc43bad39e77cf26/webvirtcloud.sh#L477C5-L477C180

Perhaps Debian 11 comes with those package by default? Or it could be that my system is headless and thus they are not installed by default.

It looks like this issue could be fixed by adding these packages to the Installer script.

**Comment by catborise** [comment]
thank you very much. i add specified packages to installer.
