### ISSUE TITLE
Network Bug after the last update

### ISSUE THREAD

**Issue by thiagocpv** [retspen/webvirtcloud#61]
Hi there!

After the last webvirtcloud update, there is a bug to create new instance.
The bug is on the network config. After create the instance, install de O.S and config the network IP, the instance cannot ping the gateway or any host. To solve this, I need copy a old xml file, rename the special fields e paste in the new instance. After this the network is reacheable.

Can anyone test this please?

Thanks.

**Comment by retspen** [comment]
You need rebuild your instances or change XML and remove ```<filterref filter='clean-traffic'/>```

**Comment by thiagocpv** [comment]
Thank you!

**Comment by balthild** [comment]
I installed latest `master` branch version today. The xml still contains a `<filterref filter='clean-traffic'/>` line.
