### ISSUE TITLE
Unable to authenticate to compute instance 

### ISSUE THREAD

**Issue by grebois** [retspen/webvirtcloud#63]
I've created 2 users with saslpasswd2;

    root@vhstage02:~# sasldblistusers2 -f /etc/libvirt/passwd.db
    root@vhstage02: userPassword
    admin@vhstage02: userPassword

When adding a compute instance using TCP I'm getting;

![screen shot 2015-10-22 at 14 24 34](https://cloud.githubusercontent.com/assets/1569751/10665071/b86cb3f4-78c8-11e5-84c7-6ff894f16379.png)

Checking the logs ( /var/log/supervisor/webvirtcloud-stdout---supervisor-UIcT_0.log ) I see;

    libvirt: XML-RPC error : authentication failed: authentication failed

When adding a compute instance using socket I'm getting;

    libvirt: Polkit error : authentication failed: no agent is available to authenticate

Any idea what might I be missing? Thanks!

**Comment by savichev** [comment]
use login fdqn ('root@vhstage02' or 'admin@vhstage02')

**Comment by grebois** [comment]
That worked perfectly, thanks.
