### ISSUE TITLE
[Feature request] noVNC Keymap Configurable?

### ISSUE THREAD

**Issue by petzsch** [retspen/webvirtcloud#86]
I would like to use a german keymap with noVNC. This is possible with Archipel and Proxmox (both use noVNC as well). Maybe make the default keyboard layout an option in the users profile?

**Comment by savichev** [comment]
![Image of Yaktocat]
(https://doc-0c-c0-docs.googleusercontent.com/docs/securesc/m6huoks7vjtlotrundlfo3896grdb54o/k1re1opdr2ga44jujupmk950huob3emv/1455307200000/08622166791824656467/08622166791824656467/0B3nCYjrmYCx0ZmlUNGs0RV95UEE?e=download&nonce=tl2tu291i4c1c&user=08622166791824656467&hash=nqkot0fa7nnaopt8hfbrp8vrjvau887i)

**Comment by petzsch** [comment]
Just found the config option under Instance-> Settings-> VNC.
