### ISSUE TITLE
vnc listens on 0.0.0.0

### ISSUE THREAD

**Issue by xdtianyu** [retspen/webvirtcloud#95]
Machines created by `webvirtcloud` and `webvirtmgr` is setting `vnc` listen on `0.0.0.0`, I think it's not safe.

I have modified `vrtManager/create.py` from 

```
<graphics type='%s' port='-1' autoport='yes' listen='0.0.0.0'>
    <listen type='address' address='0.0.0.0'/>
</graphics>
```
to
```
<graphics type='%s' port='-1' autoport='yes'/>
```

But it seems `noVnc` is not working with `vnc` listen on `127.0.0.1`, I'm using socket connection, so I modified `console/webvirtmgr-console` and `console/novncd` from
```
elif console_socket or re.match('^127\.', console_host):
```
to 
```
elif console_socket or (re.match('^127\.', console_host) and conntype != CONN_SOCKET):
```
and everything works fine.  Is this a bug or something designed on purpose?

**Comment by nitmir** [comment]
The main problem I tkink is that there is no VNC password by default, so anyone can connect to the VM VNC.
As long that no password is defined for the VNC connection, I think VNC should only listen locally and preferably to a unix socket where only novnc console (with token auth) has access.

If the user set a VNC password later, then `webvirtcloud` or `webvirtmgr` can bind VNC to 0.0.0.0.

**Comment by nitmir** [comment]
Hum, I think that the best solution is maybe to add a field `vnc_default_bind_address` to the model class `Compute` with default value `0.0.0.0` for TCP and TLS connections and `127.0.0.1` with SSH connection and Local Socket, and let users choose their default bind address on a by hypervisor basis.

Any thought ?
